### ISSUE TITLE
BBOX tests can fail due to precision issues

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#106]
I have a dataset with just two EPSG 4326 points having the following coordinates:
- -66.16667 18.66667
- -66.71667 18.00126

The BBOX tests sample those points, get the overall bbox, and then use geomatrics-tgeotk Extends.evenlopeAsGML method to turn that into a BBOX usable for a filter. Unfortunately the method formats with just 2 decimal digits (definitely not enough for geographic coordinates) and ends up building a request as follows:

```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                startIndex="0"
                version="2.0.0">
   <wfs:Query xmlns:ns97="http://www.opengeospatial.org/projects/initiatives/geoedgeplugfest"
              typeNames="ns97:port_p">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:BBOX>
            <fes:ValueReference xmlns:tns="http://www.opengeospatial.org/projects/initiatives/geoedgeplugfest">tns:wkb_geometry</fes:ValueReference>
            <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4326">
               <gml:lowerCorner>-66.71 18</gml:lowerCorner>
               <gml:upperCorner>-66.16 18.66</gml:upperCorner>
            </gml:Envelope>
         </fes:BBOX>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>
```

The first point is not captured by the request as it sits slightly north of the bounds, while the second sits slightly west of the bounds. No features get captured, and the test end up failing.
Unfortunately the method does not allow customizing the precision, I guess the only approach would be to expand the extends a bit before formatting them. I'll follow up with a pull request.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by aaime** [comment]
I already have a fix, I'm writing tests for it

**Comment by aaime** [comment]
Tentative fix here: https://github.com/opengeospatial/ets-wfs20/pull/107 (works for me)
