### ISSUE TITLE
Test engine should not prune query parameters from capabilities endpoints

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#108]
The current testing code removes query parameters from the capabilities endpoints.
For example, if the capability reports this as the transaction endpoint:
``http://cloudsdi.geo-solutions.it:80/geoserver/sf/wfs?authkey=<valueHere>``
the request will actually be made to:
``http://cloudsdi.geo-solutions.it:80/geoserver/sf/wfs``

In the above case, this breaks WFS-T usage because writing is not allowed to the anonymous user. 
The authkey parameter is a simple authentication mechanism, used when clients do not support basic/digest auth (like CITE tests).
But this is not the only case, for example mapserver often add the mapfile location as a query parameter in the endpoints, removing it obviously breaks usage in that case too.

OWS does not say that one should only provide a URL with path and no query string, the tests should respect that.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment]
Unfortunately, I had to revert the pull request as a "?" is always added afterwards. This causes duplicate "?" in request URL (e.g. ```http://service.com?&?service=WFS&request=GetCapabilities```).

For example, RI will not pass any more: http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities
