### ISSUE TITLE
status code 500 error for test "basic wfs > comparisonOperatorTests > invalidOperand_boundedBy"

### ISSUE THREAD

**Issue by zguo** [opengeospatial/ets-wfs20#110]
This issue occurs with test basic wfs > comparisonOperatorTests > invalidOperand_boundedBy

**request**
`service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0&typenames=ns95:AdministrativeUnit&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns95,http://inspire.ec.europa.eu/schemas/au/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Ans95%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fau%2F4.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%3E%3CPropertyIsLessThanOrEqualTo%20matchAction%3D%22Any%22%20matchCase%3D%22true%22%3E%3CLiteral%3E%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20srsName%3D%22urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326%22%3E%3Cgml%3AlowerCorner%3E-90%20-180%3C%2Fgml%3AlowerCorner%3E%3Cgml%3AupperCorner%3E90%20180%3C%2Fgml%3AupperCorner%3E%3C%2Fgml%3AEnvelope%3E%3C%2FLiteral%3E%3CValueReference%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%3Egml%3AboundedBy%3C%2FValueReference%3E%3C%2FPropertyIsLessThanOrEqualTo%3E%3C%2FFilter%3E`

**response**
`<?xml version="1.0" encoding="UTF-8" ?><ExceptionReport xmlns="http://www.opengis.net/ows/1.1" version="2.0.0" ><Exception exceptionCode="OperationProcessingFailed" locator="GetFeature" ><ExceptionText><![CDATA[Server processing failed]]></ExceptionText><ExceptionText><![CDATA[Server processing failed Incompatible datatypes in comparison.]]></ExceptionText></Exception></ExceptionReport>`

 
**validation error**
OGC TEAM Engine reported a failed test: Expected status code(s) [400, 403] but received 500. expected [true] but found [false]

**Analysis**
based on spec in http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#411

status code 500 should be valid for exception OperationProcessingFailed

**Comment by lgoltz** [comment]
@zguo Can you provide details of the environment you was testing on ([prod](http://cite.opengeospatial.org/teamengine/) or [beta](http://cite.opengeospatial.org/te2/) or a local setup) ? If you are testing locally, which version of the TEAM Engine and ETS was used? 

As far as I see the status code is already added as expected status code with pull request #76 (in 1.28), see #73.

**Comment by dstenger** [comment]
The latest version of ets-wfs20 contains many bug fixes compared to the one installed on http://cite.opengeospatial.org/teamengine/.
The latest version is installed on OGC beta web site and is also publicly available: http://cite.opengeospatial.org/te2/

An update of http://cite.opengeospatial.org/teamengine is planned for the next months.

**Comment by zguo** [comment]
thanks!
