### ISSUE TITLE
"Index: 0, Size: 0" error for test "temporal filter > AfterTests > afterInstant"

### ISSUE THREAD

**Issue by zguo** [opengeospatial/ets-wfs20#111]
This issue occurs with temporal filter > AfterTests > afterInstant

**request**
?service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0

**response**

`<?xml version="1.0" encoding="UTF-8" ?><ExceptionReport xmlns="http://www.opengis.net/ows/1.1" version="2.0.0" ><Exception exceptionCode="MissingParameterValue"  locator="TYPENAMES" ><ExceptionText><![CDATA[Operation request does not include a parameter value, and this server did not declare a default value for that parameter.]]></ExceptionText><ExceptionText><![CDATA[Operation request does not include a parameter value, and this server did not declare a default value for that parameter. The mandatory parameter TYPENAMES is missing.]]></ExceptionText></Exception></ExceptionReport>`

**validation error**

OGC TEAM Engine reported a failed test: Index: 0, Size: 0

**Analysis**
In order to return records, the request need to have TYPENAMES parameter as the parameter is  mandatory

**Comment by lgoltz** [comment]
@zguo Thanks for reporting this. Can you provide details of the environment you was testing on ([prod](http://cite.opengeospatial.org/teamengine/) or [beta](http://cite.opengeospatial.org/te2/) or a local setup) ? If you are testing locally, which version of the TEAM Engine and ETS was used? 

Can you provide the service URL for testing?

**Comment by zguo** [comment]
We are testing OGC compliance using INSPIRE validator downloaded from https://github.com/etf-validator/etf-webapp/releases on a testing environment, I believe it is pointing to the version on http://cite.opengeospatial.org/teamengine, we just downloaded latest ets-wfs20 from here and tried it, our developer confirmed the issue happens with the latest as well. 

the test service is located at http://inspiredemo.esri.com:6080/arcgis/rest/services/au/MapServer/exts/InspireFeatureDownload/service?Request=GetCapabilities&service=WFS

Thanks,

**Comment by lgoltz** [comment]
The failure is already described in #84 (I've closed this as duplicate). 

It depends on the provided GML application schema. If the available temporal property is configured as 

```
<element name="legalFoundationDate" nillable="true">
  <annotation>
    <documentation>-- Definition --...</documentation>
  </annotation>
  <complexType>
    <simpleContent>
      <extension base="dateTime">
        <attribute name="nilReason" type="gml:NilReasonType" />
      </extension>
    </simpleContent>
  </complexType>
</element>
```
the ETS is not able to parse this as feature property.

**Comment by lgoltz** [comment]
PR #113 should fix the problem (at least for http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities). The service http://inspiredemo.esri.com:6080/arcgis/rest/services/au/MapServer/exts/InspireFeatureDownload/service?Request=GetCapabilities&service=WFS is not longer available (OutOfMemory).

**Comment by lgoltz** [comment]
Thanks. The failure message is now `java.lang.IllegalArgumentException: Empty Set<TemporalGeometricPrimitive>`.
This occurs cause the selected temporal property (`beginLifespanVersion`) of the feature type `AdministrativeBoundary` does not contain any data. I will try to imrpove the failure message.
Maybe we should skip the test if no sufficient test  data are available (this is already done if no temporal property was found).
