### ISSUE TITLE
Improve test StoredQueryTests#invokeGetFeatureById() and documentation

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#122]
## Current documentation:
**entry page of the test**
`A feature identifier may be supplied for the purpose of verifying the behavior of the GetFeatureById stored query. If this test run parameter is missing or does not identify an available feature instance, a "Simple WFS" implementation must also implement the GetFeatureByType stored query (see the test suite documentation for the definition). The parameter may be omitted if the WFS under test implements the "Basic WFS" conformance class. `

**suite**
http://cite.opengeospatial.org/teamengine/about/wfs/2.0.0/site/ (Section "Test requirements)

## Implementation
The implementation uses the passed feature id from the user if available or the gml:id from a feature of the first feature type: https://github.com/opengeospatial/ets-wfs20/blob/22edc8f01a723fe0da53eecd0d786ce53c505264/src/main/java/org/opengis/cite/iso19142/simple/StoredQueryTests.java#L159-L164

If no feature id is available the test fails.

## Proposal
* Update the documentation and explain how get the feature id.
* Update the documentation and explain the fallback (existing feature id is used).
* Enhance the test and try to get a feature id not only from the first feature type.
* Skip test (instead fail) if feature id is not available.

**Comment by lgoltz** [comment]
> Enhance the test and try to get a feature id not only from the first feature type.

Implementation was updated: https://github.com/opengeospatial/ets-wfs20/commit/fc3abfa3fb95d9951f7e4f1e2b681e07ffad1166

> Skip test (instead fail) if feature id is not available.

Should we really skip the test? The test requirements claims that "Data are available for at least one feature type advertised in the capabilities document." (http://cite.opengeospatial.org/teamengine/about/wfs/2.0.0/site/).

@dstenger: Shall we remove the possibility to pass a feature identifier?

**Comment by dstenger** [comment]
I propose to remove possibility to pass a feature identifier.

**Comment by lgoltz** [comment]
> I propose to remove possibility to pass a feature identifier.

Done: https://github.com/opengeospatial/ets-wfs20/commit/22f9b0f793300faa90a367c6ed51e024a1117a9c

> Skip test (instead fail) if feature id is not available.

We decided not to skip the tests.
