### ISSUE TITLE
Locking tests are executed although locking is not supported

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#124]
SUT: http://cloudsdi.geo-solutions.it/geoserver/geoedge/ows?request=GetCapabilities&service=WFS
Version: 1.30-SNAPSHOT

LockingCapabilitiesTests.implementsLockingWFS() (annotated with @BeforeTest) fails with "Unexpected result evaluating XPath expression with context node #document:                      //ows:Constraint[@name='ImplementsLockingWFS']/ows:DefaultValue = 'TRUE'"

Several locking tests fails, e.g. LockFeatureTests.lockAllFeaturesByType() with `com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalArgumentException: URI is not absolute` cause no endpoint for the LockFeature operation can be found.

It is expected that the lock tests are skipped if locking is not supported by the service.

**Comment by keshav-nangare** [comment]
@lgoltz 

While testing the ets with RI[1] I got the following error:
```
Error: DescribeFeatureType request endpoint (GET method) not found in capabilities.

Test Name : tns:Main type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: DescribeFeatureType request endpoint (GET method) not found in capabilities.
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:600)
	at com.occamlab.te.TECore.executeTest(TECore.java:811)
	at com.occamlab.te.TECore.execute_test(TECore.java:419)
	at com.occamlab.te.TECore.execute_suite(TECore.java:467)
	at com.occamlab.te.TECore.execute(TECore.java:296)
	at com.occamlab.te.TECore.run(TECore.java:2403)

```

This issue is occured due to the different namespaces in ets and the service for `ows`.
Following are the namespace-uri: 
```
ets     : http://www.opengis.net/ows/1.1
service : http://www.opengis.net/ows/2.0
```
So the URI are different that's why xpath(`//ows:Operation[@name='DescribeFeatureType']//ows:Get/@xlink:href`) is failed to retrive the result from service.

[1] http://cloudsdi.geo-solutions.it/geoserver/geoedge/ows?request=GetCapabilities&service=WFS

**Comment by lgoltz** [comment]
@keshav-nangare Ok, seems the service capabilities document has changed. We can postpone this issue until the it is fixed.

**Comment by keshav-nangare** [comment]
@lgoltz 

Thanks Lyn.


> LockingCapabilitiesTests.implementsLockingWFS() (annotated with @BeforeTest) fails with "Unexpected result evaluating XPath expression with context node #document: //ows:Constraint[@name='ImplementsLockingWFS']/ows:DefaultValue = 'TRUE'"

This error message is expected as the current implementation of the xpath evaluation and assertion. If we don't want this error message then we have to create separate logic to evaluate xpath.

Here is the code snippet:

https://github.com/opengeospatial/ets-wfs20/blob/98d4ee1ba7dbfeb485ff0a14ee29499500f93a9e/src/main/java/org/opengis/cite/iso19142/locking/LockingCapabilitiesTests.java#L53-L57


https://github.com/opengeospatial/ets-wfs20/blob/98d4ee1ba7dbfeb485ff0a14ee29499500f93a9e/src/main/java/org/opengis/cite/iso19142/ETSAssert.java#L96-L123

**Comment by lgoltz** [comment]
@keshav-nangare Yes, the XPath must be evaluated first and if the result is false a SkipException must be thrown.

**Comment by keshav-nangare** [comment]
@lgoltz 

I have updated the test and fixed XPath assertion which will help us to throw skip exception if the implementation of the is not found.

Fixed with this commit: 
a3d540c

**Comment by lgoltz** [comment]
The same problem applies to GetFeatureWithLockTests: sutImplementsGetFeatureWithLock fails if the service does not provide the operation GetFeatureWithLock. 
Fixed with commit: https://github.com/opengeospatial/ets-wfs20/commit/d2558efe5216c7f804aa4259194275ac091b2355
