### ISSUE TITLE
AbstractTemporalTest gives skip exception in any case

### ISSUE THREAD

**Issue by ihsanyapicioglu** [opengeospatial/ets-wfs20#130]
SUT: https://wfst.axl.aero/AxlRest/wfs?service=WFS&version=2.0.0&request=GetCapabilities
Version: 1.30

Class: AbstractTemporalTest.java
Method: findTemporalExtent

https://github.com/opengeospatial/ets-wfs20/blob/22edc8f01a723fe0da53eecd0d786ce53c505264/src/main/java/org/opengis/cite/iso19142/basic/filter/temporal/AbstractTemporalTest.java#L37

The method always return null because temporalProperty variable has never been assigned to a value. Since it is null, if condition in line 48 is always true.

https://github.com/opengeospatial/ets-wfs20/blob/22edc8f01a723fe0da53eecd0d786ce53c505264/src/main/java/org/opengis/cite/iso19142/basic/filter/temporal/AbstractTemporalTest.java#L48-L49

This situation causes findTemporalProperty method to throw SkipException in all cases.

https://github.com/opengeospatial/ets-wfs20/blob/22edc8f01a723fe0da53eecd0d786ce53c505264/src/main/java/org/opengis/cite/iso19142/basic/filter/temporal/AbstractTemporalTest.java#L27-L31

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by keshav-nangare** [comment]
Fixed with PR: #131.

Result: 
![image](https://user-images.githubusercontent.com/14732650/46820490-f21ab500-cda3-11e8-8fb3-0662b7639170.png)
