### ISSUE TITLE
HTML report is not working when using Web Browser Interface

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#134]
When Web Browser Interface is used to test WFS [1], no HTML report is displayed as test result. Just the old XML report (TestNG) is available.

Current master branch was used.

[1] http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs200?service=WFS&request=GetCapabilities

**Comment by keshav-nangare** [comment]
@dstenger 

The testng directory is not present in session directory so the teamengine is not able to generate the HTML report. As the testng dir contains the earl result and testng result. The directory is deleting the after the ETS execution somehow that leads to reported failure.

**Comment by keshav-nangare** [comment]
@dstenger 

I am able to figure out this issue and got commit which is responsible for this issue.
Following are the commits which is causing this issue:

- 3fdf6e41680515e8f497f6d62c108bc04625f008

- 02f5f04e996e492ea5a03195dd4a49e2434f2115

If we change code to `resultsDir = new File(URI.create(outputDir));` as it is then the HTML report is generating. I don't know why this method is required `FilenameUtils.normalize(outputDir)`?

**Comment by keshav-nangare** [comment]
Fixed with this commit: 724d2f70cf72ed77b7c994b742b83dd4186e1e4f
