### ISSUE TITLE
Unknown EPSG 325833

### ISSUE THREAD

**Issue by moello** [opengeospatial/ets-wfs20#137]
In Germany Brandenburg they use the EPSG 325833. Seems to be a special EPSG, I found that on the web of Brandenburg:

Das Koordinatensystem EPSG:325833 entspricht dem amtlichen Koordinatensystem im Land Brandenburg. Es handelt sich hierbei um das System EPSG:25833 mit einer zusätzlichen Überhöhung des Ostwertes um 3000 km.
Die Bezeichnung EPSG:325833 wurde nicht von der EPSG vergeben. Es ist eine landesspezifische Kodierung.

Could you make it possible, that the tests continue if there is a unknown EPSG or can this EPSG get a known EPSG?

**Comment by dstenger** [comment]
Thank you for reporting.

Thus, currently the tests are aborted if this coordinate reference system is used? Do you have a test service we can use to reproduce the behaviour?

**Comment by lgoltz** [comment]
> Thus, currently the tests are aborted if this coordinate reference system is used? Do you have a test service we can use to reproduce the behaviour?

Test service is http://cottbus.themenstadtplan.de/net3/public/ogc.ashx?NodeId=12&Service=WFS&Request=GetCapabilities (see #136).

**Comment by lgoltz** [comment]
After adding the definition of EPSG:325833 the test still fails as no binding for GetFeature requests could be found (precondition test `dataAreAvailable`). 
In the capabilities the DefaultValues of the constraints KVPEncoding and XMLEncoding (and other) are `true`, expected is `TRUE` (upper case).

**Comment by dstenger** [comment]
# Test of fix

* Test of http://cottbus.themenstadtplan.de/net3/public/ogc.ashx?NodeId=12&Service=WFS&Request=GetCapabilities with test suite.
* Error regarding EPSG code does not occur any more.

**Comment by moello** [comment]
Thanks a lot. I will wait for a new beta an meanwhile I can check the upper case problem.
