### ISSUE TITLE
exceptions for describe unknown feature type & getFeature with unknown id

### ISSUE THREAD

**Issue by VeronikaKusova** [opengeospatial/ets-wfs20#138]
I am testing our WFS via Team Engine validator and we have issues with testing steps validating exceptions and their corresponding status codes. In WFS standard (http://docs.opengeospatial.org/is/09-025r2/09-025r2.html) there is stated:
[in brackets I am giving http status codes for a mentioned exception]
- > if an operation fails because of the value of a parameter is invalid -> InvalidParameterValue (400) & OperationParsingFails (400) [WFS standard, p. 17]
-> if there is a problem during DescribeFeatureType request -> OperationParsingFailed (400) & OperationProcessingFailed (500, 400 or 403) [WFS standard, p. 60]
-> if there is a problem during GetFeature request -> OperationParsingFailed (400) & OperationProcessingFailed (500, 400 or 403) [WFS standard, p. 73]

In case of a testing step „describe unknown feature type“ the validator requires InvalidParameterValue exception 400. But we have OperationProcessingFailed (500). As described above I think OperationProcessingFailed is also correct.(?)

For „get featured by Id with unknown id“ the validator requires OperationProcessingFailed (403). But the operation fails due to an invalid parameter value. So why is not InvalidParameterValue exception  also supported? And another think is that status codes 500 and 400 should be also supported for the OperationProcessingFailed.

Test session: http://cite.opengeospatial.org/teamengine/reports/VeronikaK/s0025/html/

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

I can already confirm that status code 500 for OperationProcessingFailed was introduced by WFS 2.0.2 specification. Thus, this has to be updated in test suite.

**Comment by lgoltz** [comment]
> In case of a testing step „describe unknown feature type“ the validator requires InvalidParameterValue exception 400. But we have OperationProcessingFailed (500). As described above I think OperationProcessingFailed is also correct.(?)

In the ATS of [WFS 2.0.2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html) an InvalidParameterValue is expected:

```
A.2.22.1.1   typeNames parameter
Test Purpose: Verify that value domain of the typeNames parameter.
Test Method: From the server’s capabilities document obtain the list of  feature types that 
the server offers. Encode a request that references a  feature type that the server does 
not offer and verify that the  response is an InvalidParameterValue exception report.
```

@VeronikaKusova I assume you mean the test "invoke Get Feature By Id With Unknown I D" of the conformance class `Simple WFS`? 

The implementation of the tests [invokeGetFeatureByIdWithUnknownID](https://github.com/opengeospatial/ets-wfs20/blob/1aee4e60143c0811a376e21444817264d02080b8/src/main/java/org/opengis/cite/iso19142/simple/StoredQueryTests.java#L129) depends on the version of the WFS:
 * WFS 2.0.0: expected is 403 or 404
 * WFS 2.0.2: expected is 403

As the status code for OperationProcessingFailed is mapped to 500 in the WFS 2.0.2 specification, this must be fixed.

**Comment by jill7072** [comment]
Hi, is this fixed for 1.31 on te2? I'm still getting a test error with the following message: 
`Expected status code 404 or 403. Received: 500`

**Comment by dstenger** [comment]
Yes, this fix is installed on http://cite.opengeospatial.org/te2/.

Which test is failing with this error message?

**Comment by jill7072** [comment]
invoke Get Feature By Id With Unknown ID test for Simple WFS is failing 
![image](https://user-images.githubusercontent.com/19600343/52430121-3d2aa780-2aba-11e9-9315-1ec78b2b8ab7.png)

**Comment by dstenger** [comment]
What is the version of your service? `2.0.0` or `2.0.2`?
In case of `2.0.0` status code `500` is not allowed.
