### ISSUE TITLE
WFS test fails with "data Are Available"

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#143]
I triggered the WFS 2.0 test with the following input:

Capabilities document: http://host/ogc-wfs/wfs?service=WFS&request=GetCapabilities
FID: fid123

The test already fails at “Preconditions” saying that the “data are Available” test failed. Well, of course, the WFS serves data, not at least the object whose FID was provided as input to the test run. 

Can you help me with more context about this error? What exactly is “data are Available” testing and how can I make it pass?

**Comment by dstenger** [comment]
Hi Claus,

I analyzed the reported behavior.

The test suite sends following request to retrieve features: http://host/ogc-wfs/wfs?service=WFS&version=2.0.0&request=GetFeature&count=25&startindex=0&typenames=ns13:Building&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns13,http://www.opengis.net/citygml/building/2.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)

Unfortunately, your service does not support the parameters count and startindex and thus features cannot be retrieved.

Error message of service is: "Response paging is not supported."

However, in my understanding, parameters count and startindex shall be supported even if response paging is not activated.

Thus, you must enable your service to be capable of handling parameters count and startindex.

Regards,

Dirk

**Comment by dstenger** [comment]
Hi Dirk,

Thanks for thoroughly testing this. „count“ is supported, but indeed „startIndex“ is not. I thought that adding the constraint “ImplementsResultPaging” and setting it to “FALSE” would imply that “startIndex” is not supported.

I think this is a bit confusing. In the WFS 2.0.2 specification, the conformance class for “startIndex” was moved from “A.2.16 Standard presentation parameters” to “A.2.20 Response paging” which is optional. This is based on a CR from Clemens: https://portal.opengeospatial.org/files/54204. On the other hand, “startIndex” is still discussed in chapter “7.6.3 Standard presentation parameters” and given a default value of 0.

So this is how I would understand it now: Every WFS has to support “startIndex=0” because this is the default value. Any other value “startIndex=x” with x > 0 is then part of the “A.2.20 Response paging” conformance class and therefore optional. And by setting “ImplementsResultPaging” to “FALSE”, a WFS implementation can clearly state that it does not support it.

Is this understanding correct?

Cheers,
Claus

**Comment by dstenger** [comment]
Thank you for your deep analysis.

The CR changes Annex A "Conformance testing" but not the main chapters of specification. Thus, startIndex is still a standard parameter.
I agree that the fact that “startIndex” is still a standard presentation parameter but is tested by ResponsePaging conformance class is a bit confusing (maybe it should have been removed from standard parameters as well).

However, response paging is more than just using "count" and "startIndex" parameters. For example, the "next" and "previous" attributes are generated and filled with values in response.

So, in my opinion, “startIndex" must be supported by all implementations or, at least, do not lead to an error if existing.

As you are testing a WFS version 2.0.0, I would definitely say that "startIndex" must be supported as this specification does not include the CR yet.

**Comment by clausnagel** [comment]
Well, the `startIndex` test at A.2.20.1 says "Verify that the server correctly handles the startIndex parameter." A.2.20.1 is neither part of the "Simple WFS" conformance class (A.1.1) nor the "Basic WFS" conformance class (A.1.2).

So, I would argue that the WFS test suite should not send the `startIndex` parameter since it is optional and set to "0" per default. The `startIndex` parameter should only be send to test response paging.

I also think that it should not make a difference whether you are testing a WFS 2.0.2 or 2.0.0. I understand WFS 2.0.2 to be a bug fix version. The test suite should be implemented such that both versions are supported without difference. If, however, there have been changes to the API in WFS 2.0.2 that require different test results, then maybe it should have been named WFS 2.1.0?

**Comment by dstenger** [comment]
I agree,
in version 2.0.0 the `startIndex` parameter is tested in Simple WFS conformance class (according to abstract test suite)
and in version 2.0.2 the `startIndex` parameter is tested in Response Paging conformance class (according to abstract test suite).

However, the non-annex text of specification (chapter `Standard presentation parameters`) did not change between both versions.

Actually, it makes a difference whether version 2.0.0 or 2.0.2 is tested. If version 2.0.2 is used, the value of parameter `version` must be `2.0.2`. In case of version 2.0.0 parameter value of version must be `2.0.0`.
Thus, it is still possible to publish WFS 2.0.0 services.

This test suite is capable to test both versions.

**Comment by dstenger** [comment]
> So, I would argue that the WFS test suite should not send the startIndex=0 parameter since it is optional and set to "0" per default. The startIndex parameter should only be send to test response paging.

However, if this parameter is attached service should not throw an exception as it is not illegal to attach additional parameters.

**Comment by dstenger** [comment]
Of course, we can evaluate if `startIndex` parameter can be removed from "data Are Available" test completely.

**Comment by dstenger** [comment]
Fix was successfully tested with service provided by @clausnagel.
Test `data Are Available` is passing now.
