### ISSUE TITLE
DescribeFeatureTypeTests.describeUnknownFeatureType expects InvalidParameterValue

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#149]
s. https://github.com/opengeospatial/ets-wfs20/issues/144#issuecomment-475183232

**Comment by dstenger** [comment]
Issue is related to #147 and solution of #147 might be considered here.

**Comment by ghobona** [comment]
Closing this issue because it was solved, as shown in the referenced Issued - both of which are closed.
