### ISSUE TITLE
Update tests to use TEAM Engine 5.4

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#155]
Applies to integration and system tests.

SoapUI project must be updated as version was removed from URI to test suites of REST API (also see https://github.com/opengeospatial/teamengine/issues/261).
Please also update Maven configuration and set version of SoapUI Maven Plugin to 5.5.0.

See updated documentation: https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

Example, how this was solved for TEAM Engine tests: https://github.com/opengeospatial/teamengine/issues/400

**Comment by keshav-nangare** [comment]
Updated with this commit: 625e1d3bac74bd195e61426187441b99032387b9

**Comment by dstenger** [comment]
After fixing the integration tests, build with `mvn clean install site -Pintegration-tests` is successful.
