### ISSUE TITLE
Temporal Test fails with multiple temporal properties 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#157]
If a feature type has multiple temporal properties the test mixes the property names and values. 
Example:
 * FeatureType: CadastralParcels 
 * application schema contains several temporal properties (e.g. beginLifespanVersion, endLifespanVersion, validFrom, validTo)
 * features have values only for beginLifespanVersion  
 * the tests requests with property validTo and values from beginLifespanVersion  

Expected: use property beginLifespanVersion and the test values from beginLifespanVersion

**Comment by ghobona** [comment]
@MarcoMinghini  In reference to the recent [tweet](https://twitter.com/MarcoMinghini/status/1276069685222653952), please note that [Issue#157](https://github.com/opengeospatial/ets-wfs20/issues/157) was released in the [Beta TEAM Engine](https://cite.opengeospatial.org/te2/) in April.

**Comment by carlospzurita** [comment]
@ghobona do you happen to have a release candidate date for version 1.33 go live in the production TEAM Engine? I'm not sure if this is published on the site.

**Comment by ghobona** [comment]
All, the fix for this issue has been uploaded to the production TEAM Engine.

Cc: @dstenger
