### ISSUE TITLE
Update test "Invoke Get Feature By Id With Unknown Id" by accepting NotFound exception

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#162]
WFS 2.0.2 spec states that NotFound exception (HTTP status code 404) shall be accepted as well: http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#192

**Comment by dstenger** [comment]
In addition, BadRequest exception (status code 400) shall be removed as this is not backed by the specification (introduced by https://github.com/opengeospatial/ets-wfs20/issues/138).

**Comment by keshav-nangare** [comment]
Removed exceptions as per specification.

**Comment by ghobona** [comment]
@dstenger I'm happy with this fix, for WFS 2.0.2
