### ISSUE TITLE
join With Intersects test error

### ISSUE THREAD

**Issue by danieluct** [opengeospatial/ets-wfs20#164]
The current spatial join implementation at https://github.com/opengeospatial/ets-wfs20/blob/052e3b0dc77b1a0bd0554380aac2e2e0b88be306/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java#L175 imposes several requirements not mentioned in the standard (e.g.: there must be two distinct geometries in the feature types server by the WFS, neither of whom can be defined as gml:AbstractGeometryType, and, except in the case both of these are AbstractCurveType, one of them must be AbstractSurfaceType). Test should be skipped in case none of this test implementation requirements are fulfilled by the service.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by ghobona** [comment]
Reviewing the spec, here is what I can deduce as the source/justification of the test.

Part of Test "A.1.12 Spatial joins" in [OGC 09-025r2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html) says "Verify that conformance tests OGC 09-026r2, A.7 and A.8 are satisfied."

Part of Test "A.8	Test cases for spatial filter" in [OGC 09-026r2](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html) says "Verify that one or more additional spatial operators are listed in the filter capabilities document. Submit requests and check that the additional spatial operators work according to their description.".

So the method [SpatialJoinTests.joinWithIntersects()](https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java#L175) verifies that if the server lists the Intersect spatial operator amongst its filter capabilities, then the Intersect spatial operator works accordingly.

Now since, the method SpatialJoinTests.joinWithIntersects() currently only lists a small set of permutations of geometry types, I agree it is reasonable for the SpatialJoinTests.joinWithIntersects() to be skipped if none of the listed permutations are implemented.

@keshav-nangare @dstenger We could, for example, skip the SpatialJoinTests.joinWithIntersects() and then throw an Exception for the Test "A.8	Test cases for spatial filter" to be verified manually.

**Comment by dstenger** [comment]
The CITE team decided to add an else block to https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java#L175 which is throwing an Exception.
@ghobona Can you please provide a short text for the exception.

Further, we will update the documentation by adding a precondition to the test suite.

**Comment by ghobona** [comment]
Something like this could be added to [SpatialJoinTests.joinWithIntersects() ](https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java#L212):

```java
        else if (!this.curveProps.isEmpty() && !this.pointProps.isEmpty()) {
            // curve property
            Iterator<Map.Entry<QName, List<XSElementDeclaration>>> itrCurveProps = this.curveProps.entrySet().iterator();
            Entry<QName, List<XSElementDeclaration>> entryCurveProps = itrCurveProps.next();
            joinProperties.add(new FeatureProperty(entryCurveProps.getKey(), entryCurveProps.getValue().get(0)));
            
            // point property
            Iterator<Map.Entry<QName, List<XSElementDeclaration>>> itrPointProps = this.pointProps.entrySet().iterator();
            Entry<QName, List<XSElementDeclaration>> entryPointProps = itrPointProps.next();
            joinProperties.add(new FeatureProperty(entryPointProps.getKey(), entryPointProps.getValue().get(0)));         
        }
        else{
           Assert.fail("This test has triggered an unexpected Spatial Join condition. The Spatial Join test will need to be applied manually.");       
        } 

```

**Comment by dstenger** [comment]
@keshav-nangare Can you please add those changes to the code, test it and create a pull request?

**Comment by keshav-nangare** [comment]
@dstenger 

I have added changes as per the suggestion and created the PR #168. Tested the changes locally with service[1] but test getting skipped.

[1] https://services.interactive-instruments.de/ogc-reference-2/simple/wfs?request=getcapabilities&service=wfs

Do we have another service to test these changes?

**Comment by dstenger** [comment]
@danieluct Is it possible to provide a test service making it possible for us to verify the changes?

**Comment by ghobona** [comment]
@keshav-nangare In addition to the service provided by @danieluct , please also try this [one](https://demo.geo-solutions.it/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities).

**Comment by danieluct** [comment]
@dstenger 
This service contains only points and multipoints https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.2
We also have an older instance, which is not actively maintained and is less compliant with OGC tests, but has (multi)polygons http://gmlid.eu/RO/ENV/PADS/WFS?service=wfs&verison=2.0.0&request=GetCapabilities

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

[1] https://demo.geo-solutions.it/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities
[2] https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.2

Following are the test results after changes:
- Tested with service [1], it throws below exception
```
Fatal Error: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: Default CRS not recognized. No code ?EPSG:404000? from authority ?European Petroleum Survey Group? found for object of type ?CoordinateReferenceSystem?.; SystemID: file:/C:/TE_BASE/work/_TE_BASE_scripts_wfs_2.0.0_ctl_/wfs-suite/tns$run-ets-wfs20.fn; Line#: 50; Column#: -1
Fatal Error: Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: Default CRS not recognized. No code ?EPSG:404000? from authority ?European Petroleum Survey Group? found for object of type ?CoordinateReferenceSystem?.; SystemID: file:/C:/TE_BASE/work/_TE_BASE_scripts_wfs_2.0.0_ctl_/wfs-suite/tns$Main.test; Line#: 126; Column#: -1
```

- Tested with service [2], it worked as we expected. We can see assertion message in below result :
![image](https://user-images.githubusercontent.com/14732650/78783314-123f2a80-79c1-11ea-9773-1b566df190aa.png)

**Comment by danieluct** [comment]
Hi,
The INSPIRE validator team informed us that they are not able to check the failure message, and therefore any result requiring a manual check should be marked as skipped: https://github.com/inspire-eu-validation/community/issues/209#issuecomment-680745458 . 
Marking it as skipped instead of error also seems more in line with how ets-wfs20 deals in other cases with valid missing pre-requisites (e.g. no temporal properties on features). 

Alternatively, the test could also include the two geometry intersections still missing (points with points, and curves with curves)

**Comment by dstenger** [comment]
@danieluct Thank you for your comment. We are fine with skipping the test when the geometry type is not supported and created a new issue: https://github.com/opengeospatial/ets-wfs20/issues/175
