### ISSUE TITLE
WPS are NS or not?

### ISSUE THREAD

**Issue by iuriemaxim** [opengeospatial/ets-wfs20#178]
According to the INSPIRE Directive are WPS Network Services or not?

![image](https://user-images.githubusercontent.com/20813598/95647831-3cda7f00-0adb-11eb-8e8a-b4155d6a8310.png)

**Comment by ghobona** [comment]
@iuriemaxim [The INSPIRE Community Forum](https://github.com/inspire-eu-validation/community) would be a more appropriate place for this question.

Please re-post the question there.

**Comment by iuriemaxim** [comment]
@ghobona I appreciate your suggestion, but the question is in relation to the INSPIRE validator. So I am expecting a response here.

If the question should be rephrased, then it could be: 

There is any reason why in the validator there are no tests for WPS?

And/Or:

There is any reason why in the validator there are no tests for the harmonized SDSs (except for testing their metadata)?

**Comment by iuriemaxim** [comment]
@ghobona Sorry, now I understood that I posted the issue in a wrong location.
