### ISSUE TITLE
WFS 2.0 CITE test does not seem to use the correct endpoint and send base64 payload. 

### ISSUE THREAD

**Issue by fhoubie** [opengeospatial/ets-wfs20#179]
Test service : http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/get?request=GetCapabilities&service=WFS

Our service receives XML body using POST on the GET  endpoint.

Here is our DCP declaration:

<ows:DCP>
	<ows:HTTP>
		<ows:Get xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/get?">
			<ows:Constraint name="GetEncoding">
				<ows:AllowedValues>
					<ows:Value>KVP</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Get>
		<ows:Post xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/post">
			<ows:Constraint name="PostEncoding">
				<ows:AllowedValues>
					<ows:Value>XML</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Post>
		<ows:Post xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/soap">
			<ows:Constraint name="PostEncoding">
				<ows:AllowedValues>
					<ows:Value>SOAP</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Post>
	</ows:HTTP>
</ows:DCP>
`
https://cite.opengeospatial.org/teamengine/reports/fhoubie1/s0002/result/describeAllFeatureTypes598598.html#describeAllFeatureTypes598598

Passing the INSPIRE validation Direct_WFS test, we have a specific endpoint for SOAP but requests are received on POST endpoint. 

Other question, we do receive a full SOAP Binary request, hence the error on the 'Binary' from our service

Intergraph.GeoMedia.Web.SDI.Common.SDIProFacadeInterface.MessageAnalyzers.XmlBodyMessageAnalyzerBase [(null)] - <Binary>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c29hcDpFbnZlbG9wZSB4bWxuczpzb2FwPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VudmVsb3BlLyI+PHNvYXA6Qm9keT48d2ZzOkdldENhcGFiaWxpdGllcyB4bWxuczp3ZnM9Imh0dHA6Ly93d3cub3Blbmdpcy5uZXQvd2ZzLzIuMCIgeG1sbnM6b3dzPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L293cy8xLjEiIHNlcnZpY2U9IldGUyI+CiAgPG93czpBY2NlcHRWZXJzaW9ucz4KICAgIDxvd3M6VmVyc2lvbj4xMC4wLjA8L293czpWZXJzaW9uPgogICAgPG93czpWZXJzaW9uPjIuMC4wPC9vd3M6VmVyc2lvbj4KICAgIDxvd3M6VmVyc2lvbj4xLjEuMDwvb3dzOlZlcnNpb24+CiAgPC9vd3M6QWNjZXB0VmVyc2lvbnM+Cjwvd2ZzOkdldENhcGFiaWxpdGllcz48L3NvYXA6Qm9keT48L3NvYXA6RW52ZWxvcGU+</Binary>

   <Exception exceptionCode="OperationNotSupported" locator="Binary">
      <ExceptionText>The operation 'Binary' is not supported by this service.</ExceptionText>
   </Exception>
</ExceptionReport></cnt:rest>

**Comment by dstenger** [comment]
@fhoubie 

I checked the specifications (WFS 2.0 and OWS Common 1.1) for following declaration:

> <ows:Post xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/soap">
> <ows:Constraint name="PostEncoding">
> ows:AllowedValues
> ows:ValueSOAP</ows:Value>
> </ows:AllowedValues>
> </ows:Constraint>
> </ows:Post>

However, I could not find any hint that a SOAP endpoint can be defined by using `ows:AllowedValues`.

**Comment by fhoubie** [comment]
@dstenger I think it is part of the SOAP HTTP Binding Status document [here](https://inspire.ec.europa.eu/reports/ImplementingRules/network/SOAP_binding_survey.pdf)

**Comment by fhoubie** [comment]
It is also part of the WMTS e-Learning document of OGC [here](http://opengeospatial.github.io/e-learning/wmts/text/operations.html#example-getcapabilities-response-soap)

**Comment by keshav-nangare** [comment]
I have updated `getOperationEndpoint` method so that evaluate XPATH for `AllowedValues` values:
1. `AllowedValues` available:
    1. Check for `binding == SOAP` and return endpoint for which `AllowedValues == SOAP`.
    2. For `GET/POST` binding return endpoint according to earlier implementation.
2. `AllowedValues` not available:
    1. For `GET/POST/SOAP` binding return endpoint according to earlier implementation (i.e for SOAP return POST).

**Comment by dstenger** [comment]
@keshav-nangare Please see my comment in the pull request.

**Comment by keshav-nangare** [comment]
I have added condition. Please find the changes in the same PR.
