### ISSUE TITLE
Deegree not passing revision 1.20

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs20#18]
Deegree server [1] is failing the test. Other reference implementations [2] are passing.

[1] http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs200?
[2] https://github.com/opengeospatial/cite/wiki/Reference-Implementations

**Comment by rjmartell** [comment]
This issue pertains to a particular service implementation, not the test suite per se. Other reference implementations are known to pass without any errors.

Several response entities appear to be not well-formed.

**Comment by jmfischer** [comment]
In [2] **GML 3.2.1 Interactive Instruments XtraServer 4.4** the url is: 

http://services.interactive-instruments.de/cite2013wfs/simpledemo/cgi-bin/cities-postgresql/wfs?request=GetFeature&service=WFS&version=2.0.0&TYPENAMES=ci:City&COUNT=10&NAMESPACES=xmlns%28ci,http://www.interactive-instruments.de/namespaces/demo/cities/4.0/cities%29

**Comment by bermud** [comment]
Simple is passing. Deegree is not implementing other conformance classes.
@rjmartell,  should we have a selection for implementers when starting the test, that they only want to test for the simple conformance class

**Comment by dstenger** [comment]
there were small fixes necessary for four tests which fail the Basic CC. These have already be done and will be part of the next upgrade of the reference implementation. The other four failures can be solved via configuration.

Is there anything further we can do?

**Comment by bermud** [comment]
@rjmartell, please improve the test so implementers can pick the conformance classes they want to test, if not provided, then configure a good default.

**Comment by rjmartell** [comment]
The capabilities document must identify the implementation status of all conformance classes as required by the WFS 2.0 spec (OGC 09-025r1), Table 13. This list determines which tests are run.

**Comment by rjmartell** [comment]
There is an issue with some _Basic WFS_ tests in the current test suite release (1.21). For example, this GET request

    http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs200?service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0&typenames=ns73:ProtectedSite&namespaces=xmlns%28xml,http://www.w3.org/XML/1998/namespace%29,xmlns%28ns73,urn:x-inspire:specification:gmlas:ProtectedSites:3.0%29,xmlns%28wfs,http://www.opengis.net/wfs/2.0%29&filter=%3Cfes%3AFilter%20xmlns%3Ans73%3D%22urn%3Ax-inspire%3Aspecification%3Agmlas%3AProtectedSites%3A3.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3ABBOX%3E%3Cfes%3AValueReference%20xmlns%3Atns%3D%22urn%3Ax-inspire%3Aspecification%3Agmlas%3AProtectedSites%3A3.0%22%3Etns%3Ageometry%3C%2Ffes%3AValueReference%3E%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20srsName%3D%22urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326%22%3E%3Cgml%3AlowerCorner%3E-90%20-180%3C%2Fgml%3AlowerCorner%3E%3Cgml%3AupperCorner%3E90%20180%3C%2Fgml%3AupperCorner%3E%3C%2Fgml%3AEnvelope%3E%3C%2Ffes%3ABBOX%3E%3C%2Ffes%3AFilter%3E

Produces a malformed response entity that cannot be parsed:

````
<?xml version='1.0' encoding='UTF-8'?>
<wfs:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd urn:x-inspire:specification:gmlas:ProtectedSites:3.0 http://cite.deegree.org/deegree-webservices-3.3.14/services/wfs200?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=DescribeFeatureType&amp;OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&amp;TYPENAME=ps:ProtectedSite&amp;NAMESPACES=xmlns(ps,urn%3Ax-inspire%3Aspecification%3Agmlas%3AProtectedSites%3A3.0)" xmlns:wfs="http://www.opengis.net/wfs/2.0" timeStamp="2016-02-16T19:04:31Z" xmlns:gml="http://www.opengis.net/gml/3.2">
  <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
    <ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>Error performing query by operator filter: Points of LinearRing do not form a closed linestring</ows:ExceptionText>
    </ows:Exception>
  </ows:ExceptionReport>
````

**Comment by rjmartell** [comment]
Also, a new test (inconsistentFeatureIdentifierAndType) is skipped because there are data for only one feature type. This test tries to set the `ResourceId` param value for an instance that does **not** match the specified type (an exception is expected); instances for at least two feature types must be available to run this test.

**Comment by dstenger** [comment]
deegree 3.3.14 is not passing all Basic CC tests and those failures are known issues. Just the Simple CC is passing.
