### ISSUE TITLE
WFS20 ComparisonOperatorTests Request Contains Invalid Parameter

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#183]
To OGC Team,

The following test failed:

property Is Greater Than_match Any

Class Name:ComparisonOperatorTests
Method Name:propertyIsGreaterThan_matchAny29
Path:org/opengis/cite/iso19142/basic/filter/ComparisonOperatorTests

Error:
java.lang.AssertionError: Unexpected HTTP status code. expected <br>[200] but found <br>[400]

This occurred from an invalid REST Request that was generated by the Validator.

The following request was generated: 

http://agsinspire1.esri.com/arcgis/rest/services/PSTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns43:ProtectedSite&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns43,http://inspire.ec.europa.eu/schemas/ps/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Ans43%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fps%2F4.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%3E%3CPropertyIsGreaterThan%20matchAction%3D%22Any%22%20matchCase%3D%22true%22%3E%3CLiteral%3E1799-12-31T00%3A03%3A58-04%3A56%3A02%3C%2FLiteral%3E%3CValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fps%2F4.0%22%3Etns%3AlegalFoundationDate%3C%2FValueReference%3E%3C%2FPropertyIsGreaterThan%3E%3C%2FFilter%3E

Decoded request:

http://agsinspire1.esri.com/arcgis/rest/services/PSTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns43:ProtectedSite&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns43,http://inspire.ec.europa.eu/schemas/ps/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=<Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ns43="http://inspire.ec.europa.eu/schemas/ps/4.0" xmlns:wfs="http://www.opengis.net/wfs/2.0"><PropertyIsGreaterThan matchAction="Any" matchCase="true"><Literal>1799-12-31T00:03:58-04:56:02</Literal><ValueReference xmlns:tns="http://inspire.ec.europa.eu/schemas/ps/4.0">tns:legalFoundationDate</ValueReference></PropertyIsGreaterThan></Filter>

The <Literal> datetime value seems to be the issue.
1799-12-31T00:03:58-04:56:02

It seems the datetime format is not correct.

If I change the datetime to the following the request succeeds.
1799-12-31T00:03:58

Can someone verify this?

[PS_GetCapabilities.zip](https://github.com/opengeospatial/teamengine/files/5557047/PS_GetCapabilities.zip)

**Comment by dstenger** [comment]
@keshav-nangare Can you please take a look at the described behavior?

**Comment by dstenger** [comment]
The part behind the "-" ( 1799-12-31T00:03:58-04:56:02) is setting the timezone.
However, I would expect something like this "-01:00".
@keshav-nangare Can you please check why there are three digits behind the "-"?

**Comment by keshav-nangare** [comment]
@dstenger 

I did some workaround about the timezone. If we use a timezone, the offset will be calculated based on its history and the valid offset at that date and time.
Example: In India, here is the [reference](https://www.timeanddate.com/time/zone/india/kolkata?) link for time offset changed over the years 
|Period|Original Date|Timezone Date with offset|
|---|---|---|
|Before 1940|1799-12-31T00:00:00|1799-12-31T00:23:28+05:53:28|
|After 1940|1940-03-20T00:00:00|1940-03-20T00:00:00+05:30|

Also, I found the difference between the response of the request made using the time offset and without the time offset.

Request 1: 
`http://agsinspire1.esri.com/arcgis/rest/services/PSTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns20:ProtectedSite&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns20,http://inspire.ec.europa.eu/schemas/ps/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=<Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ns20="http://inspire.ec.europa.eu/schemas/ps/4.0" xmlns:wfs="http://www.opengis.net/wfs/2.0"><PropertyIsGreaterThanOrEqualTo matchAction="Any" matchCase="true"><Literal>1799-12-31T00:23:28-01:00</Literal><ValueReference xmlns:tns="http://inspire.ec.europa.eu/schemas/ps/4.0">tns:legalFoundationDate</ValueReference></PropertyIsGreaterThanOrEqualTo></Filter>`

Request 2: 
`http://agsinspire1.esri.com/arcgis/rest/services/PSTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns20:ProtectedSite&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns20,http://inspire.ec.europa.eu/schemas/ps/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=<Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ns20="http://inspire.ec.europa.eu/schemas/ps/4.0" xmlns:wfs="http://www.opengis.net/wfs/2.0"><PropertyIsGreaterThanOrEqualTo matchAction="Any" matchCase="true"><Literal>1799-12-31T00:23:28</Literal><ValueReference xmlns:tns="http://inspire.ec.europa.eu/schemas/ps/4.0">tns:legalFoundationDate</ValueReference></PropertyIsGreaterThanOrEqualTo></Filter>`

**Comment by dstenger** [comment]
I checked the specifications regarding this issue:

WFS 2.0 spec (http://docs.opengeospatial.org/is/09-025r2/09-025r2.html) references Filter Encoding spec (OGC 09-026r2).
Filter Encoding spec (https://docs.opengeospatial.org/is/09-026r2/09-026r2.html) states the following:
```
7.9.3 Time zone handling

When temporal operators are used to compare time instants or periods, the time offset for local time zone shall be handled as described in XML Schema Part 2, 3.2.7: Datatypes (see W3C XML Schema Part 2).
```
W3C XML Schema Part 2 (https://www.w3.org/TR/xmlschema-2/) states:
```
3.2.7.3 Timezones

Timezones are durations with (integer-valued) hour and minute properties (with the hour magnitude limited to at most 14, and the minute magnitude limited to at most 59, except that if the hour magnitude is 14, the minute value must be 0); they may be both positive or both negative.
```

Thus, W3C just specifies time zones with hours and minutes and does not consider seconds.
Java 8, however, also considers seconds (see https://docs.oracle.com/javase/8/docs/api/java/time/ZoneOffset.html).

So, the test suite should limit the date time format to just use time zones with hours and minutes (no seconds).
@keshav-nangare Can you please update the formatting of datetime to not consider seconds in time zones?

**Comment by keshav-nangare** [comment]
@robblis 

Can you please provide the service for testing my changes?

**Comment by robblis** [comment]
Hi @keshav-nangare ,

The following service is available for testing.

http://agsinspire1.esri.com/arcgis/rest/services/PSTest/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image

Thanks,
Robert

**Comment by keshav-nangare** [comment]
@robblis 
Thank you for providing the service.

@dstenger 
I have tested my changes with the provided service. Please find the changes in #188 PR.

**Comment by robblis** [comment]
Hi @dstenger and @keshav-nangare ,

I just re-ran the same test and the issues are still present.

I'm wasn't sure if this was fixed yet.

Thanks,
Robert

**Comment by dstenger** [comment]
The fix is already installed on the Beta environment (https://cite.opengeospatial.org/te2/).
Can you please check if your problem is solved there?
If you still encounter a problem, please open a new issue.

**Comment by robblis** [comment]
Hi @dstenger,

I ran the test on the Beta environment, and the test passed for the ComparisonOperator.

Thanks,
Robert

**Comment by dstenger** [comment]
The version which is currently installed on Beta environment will most likely be moved to Production environment this summer.
