### ISSUE TITLE
WFS 2.0 - Using incorrect URL for Post request

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#184]
We're testing our HY theme using the WFS 2.0 test.

We are getting errors in the following test.
Class Name:PropertyIsLikeOperatorTests
Method Name:propertyIsNotLike303030
Path:org/opengis/cite/iso19142/basic/filter/PropertyIsLikeOperatorTests

Error:
java.lang.NullPointerException

The following is the URL used for the GetFeature test
http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service

However, the following is the URL for a post get feature request as listed in the GetCapabilities XML shown in the following snippet from the GetCapabilities file.
<ows:Operation name="GetFeature">
			<ows:DCP>
				<ows:HTTP>
					<ows:Get xlink:href="http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?"/>
					<ows:Post xlink:href="**http://agsinspire1.esri.com/arcgis/services/HYTest/MapServer/InspireFeatureDownload**"/>
				</ows:HTTP>

If I use the Post URL and run the request, I get the property xml returned.

This behavior is happening on other theme tests also.

[HY_GetCapabilities.zip](https://github.com/opengeospatial/teamengine/files/5569732/HY_GetCapabilities.zip)

**Comment by dstenger** [comment]
@keshav-nangare Can you please take a look at the described behavior?

**Comment by keshav-nangare** [comment]
@robblis 

Can you please provide service to analyze the reported behavior?

**Comment by robblis** [comment]
@keshav-nangare 

Not sure if you still need a service to test against. Sorry for the delay.

http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image

**Comment by keshav-nangare** [comment]
@robblis

Thank you for providing service. 

@dstenger @ghobona 

The behavior is reproducible and found that there is a problem with the schema which causes failure of the `compile XML Schema` test.

Failure reason:
```
2 schema error(s) detected.
Severity: ERROR Message: src-resolve: Cannot resolve the name 'hy-n:WatercourseLinkSequence' to a(n) 'element declaration' component. Location: line=68 column=52
Severity: ERROR Message: src-resolve: Cannot resolve the name 'hy-n:WatercourseSeparatedCrossing' to a(n) 'element declaration' component. Location: line=69 column=57
```
Can you please give your inputs?

**Comment by dstenger** [comment]
@keshav-nangare Can you please link the validated document here so that we can check if it is schema valid?

**Comment by keshav-nangare** [comment]
@dstenger 

Following are my findings:
1. The schema locations are retrieved using the following request http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=DescribeFeatureType
2. Above request response contains schema location which can be located using the following request
http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&VERSION=2.0.0&OUTPUTFORMAT=text/xml;subtype=gml/3.2.1&REQUEST=DescribeFeatureType&TYPENAMES=ns:Crossing,ns:DamOrWeir,ns:DrainageBasin,ns:Embankment,ns:Falls,ns:Ford,ns:LandWaterBoundary,ns:Lock,ns:Rapids,ns:RiverBasin,ns:Shore,ns:ShorelineConstruction,ns:Sluice,ns:StandingWater,ns:Watercourse,ns:Wetland&NAMESPACES=xmlns(ns,http://inspire.ec.europa.eu/schemas/hy-p/4.0)&
3. The XSD referred in the above response have the problems mentioned in the above comment 
http://agsinspire1.esri.com/arcgis/rest/directories/arcgisforinspire/schema/INSPIRE/hy/4.0/HydroBase.xsd

**Comment by dstenger** [comment]
Might be related to https://github.com/opengeospatial/ets-wfs20/issues/207.

**Comment by ghobona** [comment]
@robblis The service is not reachable. Please provide us with a reachable service.

**Comment by robblis** [comment]
Hi @ghobona ,

The service is back online. Please let us know if you still have connection problems.

Robert

**Comment by ghobona** [comment]
Thanks @robblis !

**Comment by bpross-52n** [comment]
@robblis The issue with the schema might be related to issue #207, see this [comment](https://github.com/opengeospatial/ets-wfs20/issues/207#issuecomment-966288356
).
The original reported issue with wrong POST URLs used for tests cannot be reproduced by us. However, we are using a different WFS instance, as the service you referenced seems to use the HTTP protocol in the capabilities document (see [here](http://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0)). 

These URLs are redirected to HTTPS and this causes problems for the tests. Would it be possible to change the URLs to https throughout the service? this way, we could test again with the original service. We then could also verify the issue with the schema. 

Thanks!

**Comment by dstenger** [comment]
We just checked on Beta (https://cite.ogc.org/te2/) if the NPE is still occurring and we can still reproduce it.
However, as @bpross-52n already mentioned, there is a problem with the HTTP status code `301 Moved Permanently` which might be the root cause of the NPE.
https://github.com/opengeospatial/teamengine/pull/513 describes how HTTP status code 301 is handled by TEAM Engine which might be migrated to this test suite.

**Comment by robblis** [comment]
Hi @dstenger,

We just updated the configuration of this service to use https schema.

https://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image

We ran the WFS test again and we are still seeing many errors and the test is reporting that it is using the GET URL for a POST call. If the report is showing the wrong URL from what it actually uses please let me know. 

However, when I run a POST call using the URL indicated in the report, I do get an exception. When I use the correct URL for a POST call then I get returned XML from the service.

Here is the first failure from the attached report.

**property Is Not Like**
--
Test Name: | property Is Not Like
--
Test Description: 
See ISO 19143: 7.7.3.4, 7.10 \| Details ↗
Class Name: PropertyIsLikeOperatorTests
Method Name: propertyIsNotLike
Path:org/opengis/cite/iso19142/basic/filter/PropertyIsLikeOperatorTests
--
Test Result: | FAILED
--
Test Requests 1: | Method: POST
URL: https://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/exts/InspireFeatureDownload/service
Body: 
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS" version="2.0.0">
   <wfs:Query xmlns:ns17="http://inspire.ec.europa.eu/schemas/hy-p/4.0" typeNames="ns17:Shore"/>
</wfs:GetFeature>

Outputs:
--
Reason of Failure: | java.lang.AssertionError: Test cannot be executed as no schema can be found; Please check if DescribeFeatureType returns a valid schema.
--

The above error seems to be the Reason of Failure for just about all the failures.

So if I use URL: https://agsinspire1.esri.com/arcgis/rest/services/HYTest/MapServer/InspireFeatureDownload and run a POST request using the above value for the Body, I get 2 features returned.

<?xml version="1.0" encoding="utf-8"?>
<wfs:FeatureCollection timeStamp="2022-07-25T14:40:36.984+01:00" numberReturned="2" numberMatched="unknown" xmlns:act-core="http://inspire.ec.europa.eu/schemas/act-core/4.0" ...


Can you re-assess this?

I've attached the report or you can run the rest yourself, using the https getCapabilities request specified at the top of this post.

Thanks,
Robert

[HYTest_WFS_Report_s0037.zip](https://github.com/opengeospatial/ets-wfs20/files/9185063/HYTest_WFS_Report_s0037.zip)

**Comment by robblis** [comment]
Hi @dstenger,

Upon further assessment, we believe the issue is with our service and missing available feature types. We will address that in our service.

We still want to point out that the report still shows the wrong URL for POST requests.

We do have some other questions about some of the errors and may need assistance, but will submit new issues as needed.

Thanks for your patience and help,
Robert
