### ISSUE TITLE
AM Theme Direct WFS GetProperty Request Fails with Generated Request

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#186]
We're running a Direct WFS Test against the AM theme.

It fails with the following:
OGC TEAM Engine reported a failed test: Node has unexpected [local name] value. expected [ValueCollection] but found [ExceptionReport]

The following is the request that was generated.

service=WFS&version=2.0.0&request=GetPropertyValue&count=100&typenames=ns67:ManagementRestrictionOrRegulationZone&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(gml,http://www.opengis.net/gml/3.2),xmlns(ns67,http://inspire.ec.europa.eu/schemas/am/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&valuereference=@gml:id

However, if I add the namespace and feature in front of the "@gml:id", shown in the request below,  I do get a returned valueCollection.

service=WFS&version=2.0.0&request=GetPropertyValue&count=100&typenames=ns67:ManagementRestrictionOrRegulationZone&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(gml,http://www.opengis.net/gml/3.2),xmlns(ns67,http://inspire.ec.europa.eu/schemas/am/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&valuereference=**ns67:ManagementRestrictionOrRegulationZone**@gml:id

We're not sure what is the solution for this.

I've attached the GetCapabilities xml file.

Thanks for any help provided.

[AM_GetCapabilities.zip](https://github.com/opengeospatial/teamengine/files/5526306/AM_GetCapabilities.zip)

**Comment by dstenger** [comment]
@keshav-nangare Can you please do further investigation?

**Comment by keshav-nangare** [comment]
@dstenger 

The current implementation sends the request with a hardcoded query parameter as `valuereference=@gml:id`. I checked the documentation and have attached the documentation for that as below:


![image](https://user-images.githubusercontent.com/14732650/100197700-acd48580-2f20-11eb-80b3-34944e8d4b2e.png)

Can you please help me with the value of the query parameter `valuereference`?

**Comment by dstenger** [comment]
@robblis 
`@gml:id` is a valid XPath. Thus, it should work as a value for query parameter `valuereference`.
So, we assume that the error can be located on the server side. What is the exact response of your server when using `valuereference=@gml:id`?

**Comment by robblis** [comment]
Hi @dstenger,

When using the valuereference=@gml:id as in the following request.

http://agsinspire1.esri.com/arcgis/rest/services/AMTest/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetPropertyValue&count=100&typenames=ns67:ManagementRestrictionOrRegulationZone&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(gml,http://www.opengis.net/gml/3.2),xmlns(ns67,http://inspire.ec.europa.eu/schemas/am/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&valuereference=@gml:id

We get the following exception

<ExceptionReport version="2.0.0" xmlns="http://www.opengis.net/ows/1.1">
<Exception locator="unknown" exceptionCode="NoApplicableCode">
<ExceptionText>
<![CDATA[Internal Server Error]]>
</ExceptionText>
<ExceptionText>
<![CDATA[Internal Server Error The mapping of PropertyName &quot;@gml:id&quot; to the SQL schema is configured incorrectly in step &quot;am:ManagementRestrictionOrRegulationZone&quot;. The gml:id attribute cannot be mapped.]]>
</ExceptionText>
</Exception>
</ExceptionReport>

**Comment by dstenger** [comment]
Thank you for providing the information.
However, it still looks like that your server is not configured correctly. Can you please check this?

**Comment by robblis** [comment]
Hi @dstenger,

We've identified the issue and fixed it on our side.

Thank you for your assistance.

Robert
