### ISSUE TITLE
Some tests are too "greedy" and produce skip verdicts

### ISSUE THREAD

**Issue by jmfischer** [opengeospatial/ets-wfs20#19]
We have an example Application Schema for training and testing purposes called "simpleDemo". There are four FeatureTypes in it: City, District, State and River. The FeatureTypes are somehow connectet to each other (embedded Features, references etc.).

Now the "Basic" test is never going to 100%, because the test expects on **every** FeatureType *numerical* or *temporal* and as well *nilable* properties. The FeatureType *City* has all of them, the other ones not, because it makes no sense to put them there and for the reason to keep the example as simple as possible.

So, what I did: I removed the FeatureTypes with the "missing" properties and left just *City* in the application and the tests reached 100%.

So my wish: make the Test less "greedy" eg. as one FeatureType has the wanted properties let the test go to 100%, as it is not realistic that a "real" WFS will have all types of properties on every FeatureType.

The full example is located here: http://services.interactive-instruments.de/cite2013wfs/simpledemo/cgi-bin/cities-postgresql/wfs?request=GetCapabilities&service=wfs

The "City only" example is here: http://services.interactive-instruments.de/cite2015/simpledemo/cgi-bin/cities-postgresql/wfs?request=GetCapabilities&service=wfs

(Note: the **cite2015** service is currently my testing service for this issue, so it might change).

BR
Jean-Michel

**Comment by rjmartell** [comment]
You mean that some tests in the Basic conformance class are skipped? For example:

    Feature type has no nillable properties: {http://www.interactive-instruments.de/namespaces/demo/cities/4.0/cities}State

It should be possible to ignore feature types that don't qualify by using a more specialized data provider that filters out non-applicable feature types. In this case, ignore feature types that don't have any nillable properties. The `protocol-featureType` provider accepts all feature types for which instances exist, hence the skips.

**Comment by jmfischer** [comment]
Yes, I meant the example you are given above. 

Does the "skipping" has any impact on getting certified in the Basic conformance class? If this is not the case it can stay as it is, but if Basic is not accepted because of the "skipping" this should be fixed.

**Comment by rjmartell** [comment]
A skip verdict here should have no bearing on a conformity assessment as long as the test was run and passed at least once. However, since support for this predicate is required for Basic conformance, if no feature type for which instances exist has nillable properties then a fail verdict should result (i.e. unable to test required functionality). This won't happen currently, so the test class `PropertyIsNilOperatorTests` needs to be modified to detect such a situation.

**Comment by rjmartell** [comment]
If the `PropertyIsNil` predicate cannot be tested (because no features exist with a nillable property), then an assertion error is thrown with the following message:

    Unable to test required capability: PropertyIsNil. No feature type for which instances exist has nillable properties.
