### ISSUE TITLE
Geology - Empty UOM Value Error

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#193]
Hi Validator Team,

We are in the process of validating our Geology theme.

We are getting the following issue when requesting the ge:Borehole feature.

_XML document 'service.xml', Borehole 'geBorehole.1': The following properties of the feature have an empty value: uom. While this is valid against the XML schema, this is not valid according to the GML model. Please correct the process that generates the GML documents._

We feel that this may be an issue with the validator.

The attached XML returns the following XML
<ge:boreholeLength>
 <swe:Quantity>
  <swe:uom code="meters"/>
  <swe:value>0.000000</swe:value>
 </swe:Quantity>
</ge:boreholeLength>

However, the test wants to see the uom value either in an xlink:href attribute, which is not logical, or in the <swe:uom> element value itself. However, being in the node value itself causes the following schema error when running through the Xpath Assertion test.
_The content of complex type definition 'swe:UnitReference' is 'empty'. This forbids any content for element <swe:uom>._

The test should check that no property of the feature is empty. But swe:uom is not a property of the feature. 
The relevant property in this case is ge:boreholeLength, which is not empty. But it seems the test recursively checks all nested element, which maybe it should not do.

I've attached our returned XML file.

Thanks for your help,
Robert

[GE_geBoreHole_Request.zip](https://github.com/opengeospatial/ets-wfs20/files/6064617/GE_geBoreHole_Request.zip)

**Comment by dstenger** [comment]
Thank you for reporting the issue.

Can you please name the test(s) which fail due to the uom problem?
Is there a test service available we can use to reproduce the behavior?

**Comment by robblis** [comment]
Hi @dstenger,

The test name that failed is: Conformance Class 'INSPIRE GML application schemas'

Service to test: http://agsinspire1.esri.com/arcgis/rest/services/gemrv/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=ge-core:Borehole&namespaces=xmlns(ge-core,http://inspire.ec.europa.eu/schemas/ge-core/4.0)

I've attached the test report.

[ge-Borehole_Test_Conformance class_ INSPIRE GML application schemas General requirements.html.zip](https://github.com/opengeospatial/ets-wfs20/files/6118221/ge-Borehole_Test_Conformance.class_.INSPIRE.GML.application.schemas.General.requirements.html.zip)

**Comment by dstenger** [comment]
Hi @robblis,
Unfortunately, I cannot help you regarding the INSPIRE validator as this issue tracker is about the OGC CITE WFS 2.0 test suite which is a different tool.
However, as far as I know, the INSPIRE validator uses the OGC CITE WFS 2.0 test suite.
But in this case, I do not see a connection between the failure and the OGC CITE WFS 2.0 test suite.
Can you please check this with the INSPIRE community? If this failure is really located in the OGC CITE WFS 2.0 test suite, can you please give further details?

**Comment by robblis** [comment]
Hi @dstenger,

Thanks for the post.

I think I was in the wrong community when I submitted this issue. 

I did re-submit this to the INSPIRE community.

Thanks,
Robert
