### ISSUE TITLE
WFS receives error in validateMembersOfGmlObjectCollection

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [opengeospatial/ets-wfs20#198]
Hi,

I cannot determine the source of the error I receive for my WFS, which is based on atmospheric conditions data. 

**WFS:** https://haleconnect.com/ows/services/org.874.c4108a11-bdbb-4461-8902-423531561a7e_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

**Error:** Die OGC TEAM Engine hat folgenden Fehler gemeldet: The property value "http://www.opengis.net/gml/3.2":AbstractObject cannot substitute for "http://www.opengis.net/gml/3.2":AbstractGML in {http://inspire.ec.europa.eu/schemas/omop/3.0}. expected [true] but found [false]

I would appreciate your help in understanding the cause of this issue.

Kind regards,
Kate

**Comment by dstenger** [comment]
Thank you for reporting.

Do you know the request which is returning properties in namespace `http://inspire.ec.europa.eu/schemas/omop/3.0`?

**Comment by Kate-Lyndegaard** [comment]
Hi @dstenger,

Looking at the server logs, I can see these requests coming from the Team Engine:

DescribeFeatureType: https://haleconnect.com/ows/services/org.874.c4108a11-bdbb-4461-8902-423531561a7e_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=DescribeFeatureType&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&TYPENAME=omso:PointObservation&NAMESPACES=xmlns(omso,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fomso%2F3.0)

Which returns a schema that imports `omop` at this location: https://haleconnect.com/ows/schemas/org.874.c4108a11-bdbb-4461-8902-423531561a7e/_/org.874/org.874.c4108a11-bdbb-4461-8902-423531561a7e_xsd_schema1.xsd

GetFeatureType: https://haleconnect.com/ows/services/org.874.c4108a11-bdbb-4461-8902-423531561a7e_wfs?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns36:PointObservation&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns36,http://inspire.ec.europa.eu/schemas/omso/3.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)

Kind regards,
Kate

**Comment by lgoltz** [comment]
The failing test validateMembersOfGmlObjectCollection (ComplexPropertyTests) is part of https://github.com/opengeospatial/ets-gml32

The test fails because of the declaration of `otherAggregation` in the schema `omop`:
```
          <element minOccurs="0" name="otherAggregation">
            <annotation>
              <documentation>-- Name --
                otherAggregation
                -- Definition --
                Any other type of aggregation.</documentation>
            </annotation>
            <complexType>
              <complexContent>
                <extension base="gml:AbstractMemberType">
                  <sequence minOccurs="0">
                    <element ref="gml:AbstractObject"/>
                  </sequence>
                  <attributeGroup ref="gml:AssociationAttributeGroup"/>
                </extension>
              </complexContent>
            </complexType>
          </element>
```
Expected is that the referenced `gml:AbstractObject` ist a substitution of `gml:AbstractGML` ( line `<element ref="gml:AbstractObject"/>`). The GML 3.2 specifiation must be checked if this is a failure in the test suite or in the schema.

**Comment by ghobona** [comment]
TODO: @ghobona to check XSD using Oxygen.

**Comment by ghobona** [comment]
Reassigning to @bpross-52n.

**Comment by dstenger** [comment]
Issue for solving the problem was created in ets-gml32 tracker: https://github.com/opengeospatial/ets-gml32/issues/65

**Comment by ghobona** [comment]
The [GetFeature response](https://haleconnect.com/ows/services/org.874.c4108a11-bdbb-4461-8902-423531561a7e_wfs?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns36:PointObservation&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns36,http://inspire.ec.europa.eu/schemas/omso/3.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)) passes xsd-based validation on both Oxygen Editor and NetBeans.

**Comment by bpross-52n** [comment]
I am getting ambiguous results validating the schema. I will ask the SWG for guidance.

**Comment by dstenger** [comment]
@ghobona is flattening the v3.2.2 schema to use it with the test suite and test if that solves this issue.

**Comment by ghobona** [comment]
The flattened schemas are at https://github.com/opengeospatial/ets-gml32/issues/69#issuecomment-1404888601

**Comment by dstenger** [comment]
After solving #251, this issue should be solved as well.
