### ISSUE TITLE
Update test suite for 2.0.2 corrigendum

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs20#20]
Allow testing a server with 2.0.0 and 2.0.2.

**Comment by rjmartell** [comment]
Section _vii._ of the [latest WFS 2.0 revision](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html) lists the CRs processed in this corrigendum. The schema is available in the [OGC schema repository](http://schemas.opengis.net/wfs/).

**Comment by bermud** [comment]
Let's wait for testbed 12, since work on WFS 2 will be advanced.

**Comment by rjmartell** [comment]
The WFS 2.0.2 corrigendum ([OGC 09-025r2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html)) includes clarifications and corrections arising from several change requests. Update the test suite accordingly.

**Comment by rjmartell** [comment]
Completed in Testbed-12.
