### ISSUE TITLE
NullPointerExceptions when validating WFS

### ISSUE THREAD

**Issue by JohannaOtt** [opengeospatial/ets-wfs20#207]
When validating [this WFS](https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0), there are a lot of NullPointerExceptions.

I already validated other WFSs before and did not run into this issue.

This issue is created as follow up of https://github.com/INSPIRE-MIF/helpdesk-validator/issues/622

**Comment by dstenger** [comment]
The schema (https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType) of this service is parsed in method compileXMLSchema() which is part of ets-gml32:
https://github.com/opengeospatial/ets-gml32/blob/a757e0cf1c3064d17700eab116a03b621d73d813/src/main/java/org/opengis/cite/iso19136/general/XMLSchemaTests.java#L91

During schema validation errors are detected:
```
Severity: ERROR
Message: src-resolve.4.2: Error resolving component 'xlink:typeType'. It was detected that 'xlink:typeType' is in namespace 'http://www.w3.org/1999/xlink', but components from this namespace are not referenceable from schema document 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'. If this is the incorrect namespace, perhaps the prefix of 'xlink:typeType' needs to be changed. If this is the correct namespace, then an appropriate 'import' tag should be added to 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'.
Location:  line=100 column=51
Severity: ERROR
Message: src-resolve.4.2: Error resolving component 'base:IdentifierPropertyType'. It was detected that 'base:IdentifierPropertyType' is in namespace 'http://inspire.ec.europa.eu/schemas/base/3.3', but components from this namespace are not referenceable from schema document 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'. If this is the incorrect namespace, perhaps the prefix of 'base:IdentifierPropertyType' needs to be changed. If this is the correct namespace, then an appropriate 'import' tag should be added to 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'.
Location:  line=20 column=73
Severity: ERROR
Message: src-resolve.4.2: Error resolving component 'base2:ThematicIdentifierPropertyType'. It was detected that 'base2:ThematicIdentifierPropertyType' is in namespace 'http://inspire.ec.europa.eu/schemas/base2/2.0', but components from this namespace are not referenceable from schema document 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'. If this is the incorrect namespace, perhaps the prefix of 'base2:ThematicIdentifierPropertyType' needs to be changed. If this is the correct namespace, then an appropriate 'import' tag should be added to 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'.
Location:  line=21 column=119
Severity: ERROR
Message: ct-props-correct.4: Error for type '#AnonType_amountInputOutputAmountType'. Duplicate attribute uses with the same name and target namespace are specified.  Name of duplicate attribute use is 'uom'.
Location:  line=192 column=26
Severity: ERROR
Message: src-resolve.4.2: Error resolving component 'gmd:PT_FreeText_PropertyType'. It was detected that 'gmd:PT_FreeText_PropertyType' is in namespace 'http://www.isotc211.org/2005/gmd', but components from this namespace are not referenceable from schema document 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'. If this is the incorrect namespace, perhaps the prefix of 'gmd:PT_FreeText_PropertyType' needs to be changed. If this is the correct namespace, then an appropriate 'import' tag should be added to 'https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?service=WFS&version=2.0.0&request=DescribeFeatureType'.
Location:  line=149 column=86
```

This leads to the behavior that no schema is added to the testContext leading to the NPEs later.
I propose to improve the error message(s) for this case.

**Comment by bpross-52n** [comment]
@JohannaOtt The error leads to this section of the XML standard: [Section 4.2](https://www.w3.org/TR/xmlschema-1/#src-resolve) . From our understanding, in order to use the xlink:typeType element, you will have to directly import the xlink schema in the original schema. Let me know if you have any comments or questions.

**Comment by dstenger** [comment]
@JohannaOtt We improved the error message for your case (not installed on Beta, yet). Do you have any additional questions and are your problems solved? If there are no further concerns to discuss, we would like to close this issue.

**Comment by JohannaOtt** [comment]
I do not have additional questions for now but would vote for leaving the ticket open until the new error messages can be tested on beta.

**Comment by dstenger** [comment]
Thank you for your feedback!

I described the process of closing issues in https://github.com/opengeospatial/ets-wfs20/issues/191#issuecomment-1021050234.
Thus, I would like to close this issue as the corresponding pull request was already merged.
The improved error message will be installed on Beta at the end of this week and, finally, the Beta update will be announced via the cite-forum mailing list.

If you would like to propose a different workflow for closing issues, please open an issue in https://github.com/opengeospatial/cite/issues. We will discuss it in the CITE team then.
