### ISSUE TITLE
Promote preconditions to test methods

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-wfs20#21]
The test run preconditions are currently implemented as configuration (@BeforeSuite) methods in the `org.opengis.cite.iso19142.Prerequisites` class. If any of these fail, all tests are skipped. However, a failing config method is not displayed by default in the HTML report--the "Config" checkbox must be selected to view them.

It would be better to promote these checks to test methods placed in a special "preconditions" group. The remaining tests would depend on this group (using the _dependsOnGroups_ property); the preconditions are executed first and dependent tests are skipped if any preconditions are not satisfied.

**Comment by rjmartell** [comment]
One disadvantage of the suggested approach is that the precondition tests must be associated with a `<test>` tag (conformance class). That is, each precondition may be run (unnecessarily) multiple times. It might be better to add the preconditions to a mandatory conformance class and set a flag which is then read to determine whether other conformance classes are run or skipped.

**Comment by bermud** [comment]
Maybe call it: preconditions conformance class.

**Comment by rjmartell** [comment]
That would be one approach, but the problem of signalling an unsatisfied precondition between conformance classes remains. Since there is always at least one mandatory conformance class, including the preconditions there makes sense. For example:

```xml
<test name="Conformance Level 1">
    <packages>
      <package name="org.opengis.cite.abc10.level1" />
    </packages>
    <classes>
      <class name="org.opengis.cite.abc10.SuitePreconditions" />
    </classes>
  </test>
```

If a test method in `SuitePreconditions` detects that a precondition is not satisfied, then a suite  attribute is set like so:

    testContext.getSuite().setAttribute("preconditions-ok", Boolean.FALSE);

A @BeforeTest method defined for some other conformance class can then check the suite attribute:

    Boolean preconditionsOk = (Boolean) testContext.getSuite().getAttribute("preconditions-ok");
    Assert.assertTrue(preconditionsOk, "One or more test suite preconditions not satisfied.");

All tests in this conformance class are skipped if any precondition was not satisfied, and the failing test in the mandatory conformance class will indicate what the problem was.

**Comment by bermud** [comment]
Maybe, instead of packaging the preconditions as a conformance class, make them part of the most basic mandatory conformance class.

**Comment by rjmartell** [comment]
The advantage of breaking out the preconditions into a separate `<test>` group is to make them more visible in the report.

````xml
<test name="Preconditions">
    <classes>
        <class name="org.example.testng.demo.SuitePreconditions"/>
    </classes>
</test>
````

If a precondition is not satisfied, it is added to the value of the "failed-preconditions" attribute, and this is checked in subsequent BeforeTest methods in other conformance classes.

````java
@BeforeTest
public void checkPreconditions(ITestContext context) {
    Object failedPreconditions = context.getSuite().getAttribute("failed-preconditions");
    if (null != failedPreconditions) {
        throw new SkipException("One or more preconditions not satisfied: " + failedPreconditions);
    }
}
````

**Comment by bermud** [comment]
How can differentiate these "Preconditions" from a conformance class. Both from a user interface point of view and a program parsing the results?
