### ISSUE TITLE
WFS 2.0 Validation - Tests seem to be executed twice or more within the Spatial filter section

### ISSUE THREAD

**Issue by Claudia-WE** [opengeospatial/ets-wfs20#211]
**Describe the bug**

**To Reproduce**
1. Go to https://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0001&stop=undefined&t=1637138009822
2. Check redundancy of test results " Non specific bouding box e.g. 

**Expected behavior**
Only one result per test

![grafik](https://user-images.githubusercontent.com/54665693/142167797-5ea066aa-605d-487d-b74c-06ae995bbac5.png)

**Additional context**
This is a follow up ticket of https://github.com/INSPIRE-MIF/helpdesk-validator/issues/658

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by bpross-52n** [comment]
@Claudia-WE The behavior is as expected in this case. The test for spatial filtering (among others) are executed for every feature type (2 in this case) and for each protocol binding (GET and POST). We will do further investigations on the NullPointerExceptions.
