### ISSUE TITLE
Test intersectsCurve fails  - ClassCastException

### ISSUE THREAD

**Issue by Claudia-WE** [opengeospatial/ets-wfs20#212]
**Describe the bug**
Within the WFS 2.0 test ClassCastExceptions are thrown for test on intersectsCurve and intersectsPolygon.
The ClassCastException is thrown to indicate that the code has attempted to cast an object to a subclass of which it is not an instance. Could you please help me to clarify what is the reason for the error message ?

**To Reproduce**
- Test the following WFS: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID3030724d-eb08-4db3-8f65-9bd0e4485e9b
- See error in test interectsCurve: Die OGC TEAM Engine hat folgenden Fehler gemeldet: No message provided. Exception class java.lang.ClassCastException

**Expected behavior**
An error message explaining the error reason.

**Comment by ghobona** [comment]
@Claudia-WE The test report does not seem to be available anymore. 

Please provide us with the URL of the service under test? If we do not hear from you by August 14th, 2022 we will close this GitHub Issue.
