### ISSUE TITLE
A specific case with the getFeatureWithHitsOnly test step at the Response paging conformance class

### ISSUE THREAD

**Issue by mpleic** [opengeospatial/ets-wfs20#213]
Hello,

our [service](http://gis.psp.hr/webservices/inspire?SERVICE=WFS&version=2.0.0&request=GetCapabilities) fails at the Response paging > org.opengis.cite.iso19142.paging.PagingTests > getFeatureWithHitsOnly test step.
It returns the following error message: _OGC TEAM Engine reported a failed test: Unexpected number of items in response. expected [2] but found [1]_

Basically, the dataset has only one feature member, so our service returns only one feature. But the test step expects exactly 2 number of features returned. Can anything be done in this specific case?

Here is the INSPIRE WFS validation report: [Test object Katastarski plan - Eksploatacijsko polje ugljikovodika Okoli - WFS.zip](https://github.com/opengeospatial/ets-wfs20/files/7650291/Test.object.Katastarski.plan.-.Eksploatacijsko.polje.ugljikovodika.Okoli.-.WFS.zip)
 
Thank you in advance,
Marko Pleić

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.
