### ISSUE TITLE
NullPointerException when running v1.38 of the WFS compliance test

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wfs20#230]
Hi, we have an automated test that runs the latest version of the WFS 2.0 compliance test against our WFS server implementation; this test started failing since v1.38, with the following exception:

CITE	>	[TestNG] Reporter com.occamlab.te.spi.executors.testng.EarlReporter@62fdb4a6 failed
CITE	>	java.lang.NullPointerException
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.isBasicConformanceClass(EarlReporter.java:451)
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.addTestRequirements(EarlReporter.java:240)
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.generateReport(EarlReporter.java:103)
CITE	>		at org.testng.TestNG.generateReports(TestNG.java:1135)
CITE	>		at org.testng.TestNG.run(TestNG.java:1081)
CITE	>		at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
CITE	>		at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
CITE	>		at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)

Could this be a regression?

**Comment by dstenger** [comment]
Thank you for reporting.
How do you execute the tests? REST Interface, Web Browser Interface, CLI or via Java directly?
Is it possible to provide a test service to reproduce the issue?

**Comment by robinhoutmeyers** [comment]
Hi, I am running it through; however, I found out that the problem is the same as https://github.com/opengeospatial/ets-wfs20/issues/205; we've reverted to v1.37, which seems to work well.

**Comment by dstenger** [comment]
Thanks for reporting back.
However, the CLI should also work with v1.38. We will take a look into this.
Can you please provide the command you used to execute the CLI? What content was provided by the used `test-run-props.xml`?

**Comment by robinhoutmeyers** [comment]
This is the content of test-run-props.xml:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties version="1.0">
  <comment>Test run arguments (ets-wfs20)</comment>
  <entry key="iut">GET_REQUEST_URL_REGEX</entry>
</properties>

This is the command that we use:

java -Duser.home=C:\Users\abc\wfs_cite_tests_home_dir -jar C:\Users\abc\wfs_cite_tests_home_dir\wfs-20-aio.jar -o file:///C:/xyz/report/junit/ tempFile.xml

**Comment by bpross-52n** [comment]
@robinhoutmeyers The WFS 2.0 test suite in version 1.38 is using a new version of teamengine. The EarlReporter is now requiring a config.xml file, see also [here ](https://github.com/opengeospatial/ets-wfs20/issues/205#issuecomment-1018332964). You could specify another environment variable named TE_BASE specifying the directory, that contains the config.xml.

**Comment by dstenger** [comment]
@robinhoutmeyers We enhanced the documentation in https://github.com/opengeospatial/ets-wfs20/pull/245. Can you please check if that solves your problem?

**Comment by dstenger** [comment]
We decided to fix the problem in TEAM Engine so that is is not mandatory to reference an external config.xml anymore: https://github.com/opengeospatial/teamengine/issues/561

**Comment by dstenger** [comment]
We decided to close the PR of this repo: https://github.com/opengeospatial/ets-wfs20/pull/245.
However, if you are interested, it describes a workaround for the problem (this comment must also be considered https://github.com/opengeospatial/ets-wfs20/pull/245#issuecomment-1316744224).
