### ISSUE TITLE
WFS 2.0 Test - Temporal filter (AfterTests) in US Theme

### ISSUE THREAD

**Issue by Dnoack49** [opengeospatial/ets-wfs20#231]
Dear OGC-Community

after testing [this WFS](https://inspire.brandenburg.de/services/us-emf_depo_wfs?service=WFS&request=GetCapabilities) (INSPIRE Annex Theme "EnvironmentalManagementFacility" of us-govserv) against the WFS 2.0 class using both, the _productive instance_ as well as the _staging instance_ we receive the following **AfterTest**-errors for the **endLifespanVersion**-property in the **Temporal Filter** conformance class:

`No temporal values found in results: property is "http://inspire.ec.europa.eu/schemas/act-core/4.0":endLifespanVersion.`

Screenshot:
![grafik](https://user-images.githubusercontent.com/8046960/179513339-6a2f1286-12ac-477d-9a90-eef1ea724f63.png)

TestReport:
[WFS-USEMF-DEPO.pdf](https://github.com/opengeospatial/ets-wfs20/files/9131974/WFS-USEMF-DEPO.pdf)

The property value is `2018-01-01T00:00:00` and the [gml file](https://inspire.brandenburg.de/services/us-emf_depo_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=us-emf:EnvironmentalManagementFacility&Count=1 ) delivered from the WFS passes the US-Theme conformance tests.

I assume this is related to the issue #185 where , up to now, it is concluded that the ETS rather "not use a timezone to filter temporal properties that are reported by a server without a time zone". Will the conformance test be altered?

Would you please give us an advice?

**Comment by dstenger** [comment]
@Dnoack49 
Yes, we are planning to alter the conformance tests. This will happen during the next months (approximately September - October).

**Comment by bpross-52n** [comment]
@Dnoack49 The temporal filter tests seem to be successful now on the beta instance, as well as the production instance of Teamengine. Could you maybe do another test run?

**Comment by Dnoack49** [comment]
@bpross-52n Thank you for the implementation. There are no more Errors within the **Temporal Filter** - Class.
However, now I receive an error under **get Features By Type** in **the Basic WFS** - Class

![grafik](https://user-images.githubusercontent.com/8046960/198001468-43d77ae3-b7fa-4d70-a543-5588d82f59c0.png)

This error did not appear before, so it is a subsequential error to be fixed.

[WFS-USEMF-DEPO.pdf](https://github.com/opengeospatial/ets-wfs20/files/9868514/WFS-USEMF-DEPO.pdf)

**Comment by dstenger** [comment]
@Dnoack49 Thank you for reporting. Can you please open a new issue for the new problem?
Is the problem originally reported in this issue fixed for you? I propose to close it then.
