### ISSUE TITLE
GE WFS Test - non Specific BBOX Test - Unexpected Results

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#234]
One of the "non Specific BBOX" tests returns the following error in both the GET and POST test runs.
"Unexpected result evaluating XPath expression with context node wfs:FeatureCollection: //wfs:member/*"

Not sure if the test had a successful response. When running the GET request in a browser and runing the POST request in Postman, I see normal GML XML returned with content.

**GET request:** 
https://inspiredemo.esri.com/arcgis/rest/services/gemr3/MapServer/exts/InspireFeatureDownload/service?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns21:HydrogeologicalObjectNatural&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns21,http://inspire.ec.europa.eu/schemas/ge_hg/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3Cfes%3AFilter%20xmlns%3Ans21%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fge_hg%2F4.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3ABBOX%3E%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20srsName%3D%22urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4258%22%3E%3Cgml%3AlowerCorner%3E38.52%2011.93%3C%2Fgml%3AlowerCorner%3E%3Cgml%3AupperCorner%3E38.54%2011.95%3C%2Fgml%3AupperCorner%3E%3C%2Fgml%3AEnvelope%3E%3C%2Ffes%3ABBOX%3E%3C%2Ffes%3AFilter%3E

**POST**
With the POST request, I used the GetFeature POST URL from the GetCapabilities XML and return is normal. If I use the POST URL shown in the report, I get an exception. Not sure which URL the test actually used. 

POST URL from Report: https://inspiredemo.esri.com/arcgis/rest/services/gemr3/MapServer/exts/InspireFeatureDownload/service

POST URL from GetCapabilities XML used: https://inspiredemo.esri.com/arcgis/services/gemr3/MapServer/InspireFeatureDownload

Body: 
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns0="http://inspire.ec.europa.eu/schemas/ge_hg/4.0"
              typeNames="ns0:HydrogeologicalObjectNatural">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:BBOX>
            <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4258">
               <gml:lowerCorner>38.52 11.93</gml:lowerCorner>
               <gml:upperCorner>38.54 11.95</gml:upperCorner>
            </gml:Envelope>
         </fes:BBOX>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>

**To Reproduce**
1. Run a WFS 2.0 test using the following URL: https://inspiredemo.esri.com/arcgis/rest/services/gemr3/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image
2. Open report '....'
3. Scroll down to Spatial Filter -> non Specific BBOX '....'

**Expected behavior**
Test Successful

**Additional context**
I've attached the test report.

Thanks for your help,
Robert

[GE_WFS_Test_s0010.zip](https://github.com/opengeospatial/ets-wfs20/files/9244480/GE_WFS_Test_s0010.zip)

**Comment by dstenger** [comment]
Thank you for reporting.

We will do further investigation.

**Comment by bpross-52n** [comment]
Hallo @roblis. When I tested the request, it returned an empty FeatureCollection. That's why the evaluation of the XPath expression fails. I tested also with the bounding box of the layer extent (180 90 -180 -90) and no features were returned.

Regarding the wrong URL in the report: That seems to be a bug in TEAM Engine, we have created an issue for this: https://github.com/opengeospatial/teamengine/issues/555

**Comment by robblis** [comment]
Hi @bpross-52n ,

We checked on the service and there was an issue with a configuration file that's been fixed. I ran the request again manually through Postman and features were returned. I then ran the WFS test in the validator again and this particular test has passed.
So, I think in this case we can mark this test closed.

**Comment by dstenger** [comment]
Thank you for the feedback. So, we close this issue now.
If you have any further problems, you are welcome to open a new issue.
