### ISSUE TITLE
GE WFS 2.0 Test - invalid Geometry Operand - java.lang.RuntimeException: Could not create envelope for feature type

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#235]
Within the WFS 2.0 test, the "invalid Geometry Operand" test fails for multiple feature types with the following error...	

java.lang.RuntimeException: Could not create envelope for feature type: {http://inspire.ec.europa.eu/schemas/ge-core/4.0}GeologicEvent

We can run the POST request using Postman and we see normal GML XML records returned. We used the body from the test report and used the POST URL from the GetCapabilities XML.

POST URL from Report: https://inspiredemo.esri.com/arcgis/rest/services/gemr3/MapServer/exts/InspireFeatureDownload/service

POST URL from GetCapabilities XML: https://inspiredemo.esri.com/arcgis/services/gemr3/MapServer/InspireFeatureDownload

Body:
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns6="http://inspire.ec.europa.eu/schemas/ge-core/4.0"
              typeNames="ns6:GeologicEvent"/>
</wfs:GetFeature>

We see the POST URL in the report doesn't seem to match what's in the GetCapabilities XML, so we're not sure if the test used the incorrect POST URL or this is some other issue. Your assistance on this would be appreciated. 

**To Reproduce**
1. Run a WFS 2.0 test using the following URL: 
 https://inspiredemo.esri.com/arcgis/rest/services/gemr3/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image '...'
2. Open report '....'
3. Scroll down to Spatial Filter -> invalid Geometry Operand '....'

**Expected behavior**
Successful Test

**Screenshots**
Screenshot of Postman request.
![image](https://user-images.githubusercontent.com/3453448/182444386-f90b3d7b-e4a8-4fb4-aeee-9ec948e335d3.png)

**Additional context**
I've attached the test report..

Thanks for your help,
Robert

[GE_WFS_Test_s0010.zip](https://github.com/opengeospatial/ets-wfs20/files/9244661/GE_WFS_Test_s0010.zip)

**Comment by dstenger** [comment]
Thank you for reporting.

We will do further investigation.

**Comment by Dnoack49** [comment]
Hello,

I just wanted to add that we run into the same type of error for the following WFS 2.0 (INPIRE Planned Land Use):
https://inspire.brandenburg.de/services/plu_bkt_welzowsued1_wfs?service=WFS&request=GetCapabilities

This test had passed before but this time an error occurs for the FeatureType Official Documentation:
`java.lang.RuntimeException: Could not create envelope for feature type: {http://inspire.ec.europa.eu/schemas/plu/4.0}OfficialDocumentation`

Attached you find the report: 
[WFS-PLU_Test Session Results.pdf](https://github.com/opengeospatial/ets-wfs20/files/9307492/WFS-PLU_Test.Session.Results.pdf)

**Comment by dstenger** [comment]
Pull request was created to fix the problem: https://github.com/opengeospatial/ets-wfs20/pull/237
