### ISSUE TITLE
HY - intersectsCurve test seems to produce invalid gml:posList

### ISSUE THREAD

**Issue by robblis** [opengeospatial/ets-wfs20#236]
Hi OGC Validator Team,

We are testing our HY feature services.

We see the following test failure regarding Spatial Filter > intersectsCurve test.

The POST Body is the following...

<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns21="http://inspire.ec.europa.eu/schemas/hy-p/4.0"
              typeNames="ns21:ShorelineConstruction">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:Intersects>
            <fes:ValueReference xmlns:tns="http://inspire.ec.europa.eu/schemas/hy-p/4.0">tns:geometry</fes:ValueReference>
            <gml:LineString xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="d1e1"
                            srsName="urn:ogc:def:crs:EPSG::4258">
               <gml:posList>54.3 9.66 54.3 9.66</gml:posList>
            </gml:LineString>
         </fes:Intersects>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>

It seems the gml:posList is not correct with both Lat Lon values being identical. (i.e. 54.3  9.66) which causes an error when requesting the feature.

The GetCapabilities URL is: https://inspiredemo.esri.com/arcgis/rest/services/A4IGDS/GeoDataServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&STOREDQUERY_ID=&LANGUAGE=&TYPENAMES=&MAXFEATURES=&COUNT=&f=image

I've attached the report files.

Thanks for any help,
Robert

[HY_WFS_Test_s0038.zip](https://github.com/opengeospatial/ets-wfs20/files/9418392/HY_WFS_Test_s0038.zip)

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by bpross-52n** [comment]
@robblis The service is currently not reachable. Could you provide the service again?

**Comment by robblis** [comment]
Hi @bpross-52n, 
Our apologies, the service is back online.

**Comment by dstenger** [comment]
@robblis We created a fix for your problem. Is it possible to bring the service back online so that we can verify if the fix solves your reported problem?

**Comment by dstenger** [comment]
@robblis Thank you!
A functional test was successful and I merged the pull request.
We will install a new release of this test suite on Beta (https://cite.ogc.org/te2/) in the coming weeks.

**Comment by robblis** [comment]
Hi @dstenger ,
Thanks for the fix. Please let me know when the new release is on Beta.

Robert

**Comment by dstenger** [comment]
@robblis We just updated Beta (https://cite.ogc.org/te2/) which now contains the fix.
