### ISSUE TITLE
Test "Intersects Polygon" sends invalid geometry

### ISSUE THREAD

**Issue by jeanmichelfischer** [opengeospatial/ets-wfs20#238]
On the Tests "intersects Polygon" the tests send an invalid geometry for intersects. This is happening on wfs:FeatureType with geometrytype point.

The send geometry contains five identical points which is an invalid polygon/LinearRing due to https://portal.ogc.org/files/?artifact_id=25355 page 27:

> This last condition says that at a point common to the two curves, nearby points cannot be common. This
> forces each common point to be a point of tangency.

And as well in 6.1.7.1 
> A LinearRing is a LineString that is both closed and simple.

Possible solution:
If the test should select some features wich intersects, it might be better to send a small BBOX around the desired "point feature". 
Or even select more than one feature and build the BBOX from them. This solution might work with other geometry types as well.

the following Request was send (as well in GET-format, but hardly readable, so here only the POST-request):

```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns14="http://www.interactive-instruments.de/namespaces/demo/cities/4.1/cities"
              typeNames="ns14:District">
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:Intersects>
            <fes:ValueReference xmlns:tns="http://www.interactive-instruments.de/namespaces/demo/cities/4.1/cities">tns:location</fes:ValueReference>
            <gml:Polygon xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="d1e1"
                         srsName="urn:ogc:def:crs:EPSG::4326">
               <gml:exterior>
                  <gml:LinearRing>
                     <gml:posList>52.52 13.4 52.52 13.4 52.52 13.4 52.52 13.4 52.52 13.4</gml:posList>
                  </gml:LinearRing>
               </gml:exterior>
            </gml:Polygon>
         </fes:Intersects>
      </fes:Filter>
   </wfs:Query>
</wfs:GetFeature>
```

As @dstenger commented in https://github.com/opengeospatial/ets-wfs20/issues/60#issuecomment-602783923 the reason for the "not 200 Response" is the invalid Geometry above.

Beste regards,
Jean-Michel

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by dstenger** [comment]
Might be related to https://github.com/opengeospatial/ets-wfs20/issues/236.

**Comment by bpross-52n** [comment]
@jeanmichelfischer Could you maybe make the service accessible?
