### ISSUE TITLE
Test AutomaticDataLocking capability

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-wfs20#24]
There are no tests for `AutomaticDataLocking`. See cl. [15.2.3.1.1](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#276) (Declaring support for locking).

> Servers that support automatic data locking, shall not require a client to lock features before operating upon them using a Transaction operation.

**Comment by ghobona** [comment]
Closing this issue. If in the future there is interest in implementing the enhancement then the issue can be reopened.
