### ISSUE TITLE
Could not resolve geotoolkit dependency

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wfs20#249]
While trying to verify https://github.com/opengeospatial/ets-wfs20/issues/230 (sorry for the late reply), I bumped upon another issue that I haven't seen before: the Maven build fails on the geotoolkit dependency:

Failed to execute goal on project ets-wfs20: Could not resolve dependencies for project org.opengis.cite:ets-wfs20:jar:1.39: Failed to collect dependencies at org.opengis.cite:ets-gml32:jar:1.29 -> org.opengis.cite:geomatics-geotk:jar:1.15 -> org.geotoolkit.pending:geotk-xml-gml:jar:3.21: Failed to read artifact descriptor for org.geotoolkit.pending:geotk-xml-gml:jar:3.21: Could not transfer artifact org.geotoolkit:geotoolkit:pom:3.21 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [geotoolkit (http://maven.geotoolkit.org/, default, releases+snapshots), maven2-repository.dev.java.net (http://download.java.net/maven/2, default, releases+snapshots)] -> [Help 1]

Do you have any idea what could be causing this?

**Comment by dstenger** [comment]
Thank you for reporting.
The same issue was already reported here: https://github.com/opengeospatial/teamengine-docker/issues/38
Also, an issue was created in geotoolkit tracker: https://github.com/Geomatys/geotoolkit/issues/20

To summarize it, Maven 3.8 blocks repositories referenced via HTTP (just HTTPS is allowed).
A simple workaround is to use Maven 3.6 which does not block HTTP repositories.
Another solution is to define a mirror in your Maven settings as documented [here](https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked).

**Comment by robinhoutmeyers** [comment]
OK thanks, we used the mirror approach; this works as expected.
