### ISSUE TITLE
Skipping tests do not provide useful information

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs20#26]
While testing some WFS services, the tests script skips all the tests, even though the capabilities document is valid. Please fix to report properly the error and provide more useful information to the service providers. Server example includes:

http://wxs.ign.fr/kolx1l3kzyi3tw8p7r1p36e7/inspire/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities

http://wfs.geonorge.no/skwms1/wfs.elf-ad?service=WFS&version=2.0.0&request=GetCapabilities

http://wfs.geonorge.no/skwms1/wfs.inspire-hy-p?service=WFS&version=2.0.0&request=GetCapabilities

![image001](https://cloud.githubusercontent.com/assets/3738898/14572564/7c053f0a-031d-11e6-99e7-42a86b467533.jpg)

---------- RM ----

It seems an invalid media type was received when attempting to acquire sample data during the initialization phase:
 
‘text/xml; subtype=gml/3.2.1;charset=UTF-8'
 
Parsing was aborted because the Content-Type header in the response message is invalid.
The subtype parameter must be quoted to make it syntactically valid (subtype="gml/3.2.1").
See <https://github.com/opengeospatial/ets-wfs20/issues/9>.
 
 Note that according to OGC 09-144r1, the GML media type should be specified as "application/gml+xml; charset=utf-8; version=3.2" (the ‘version’ parameter is optional and isn’t necessary for conformance testing). Using the generic "application/xml" media type is also fine.

**Comment by rjmartell** [comment]
The current release is 1.21, which should show a separate test group for preconditions.

![ets-wfs20-26](https://cloud.githubusercontent.com/assets/1653506/14656096/6f6ecc96-063a-11e6-9b03-b35ec37cc8db.png)

A more informative error message is now provided.
