### ISSUE TITLE
Basic WFS getFeaturesByType validation failing - unclear why

### ISSUE THREAD

**Issue by JohannaOtt** [opengeospatial/ets-wfs20#262]
**Describe the bug**
When validating [this WFS](https://haleconnect.com/ows/services/org.923.78bd4d73-a4b9-4933-b31d-8727a8130ff6_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) with the production or the beta instance (both using WFS 2.0 test in version 1.40 currently), there are error messages on the getFeaturesByType test failling that I cannot understand so far
![grafik](https://github.com/opengeospatial/ets-wfs20/assets/34163838/a50153ef-f736-4d92-bec1-3d8c8f7d933b)
It claims that "Attribute 'xlink:href' is not allowed to appear in element 'sd:referenceSpeciesId'." and similar errors for other types. I would not see why it is not allowed to appear there according to the [schema](https://haleconnect.com/ows/services/org.923.78bd4d73-a4b9-4933-b31d-8727a8130ff6_wfs?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=2.0.0).

**To Reproduce**
1. Validate the WFS linked above against the WFS 2.0 validator version 1.40.

**Expected behavior**
I would not expect the getFeaturesByType test to fail

**Screenshots**
provided in description

**Additional context**
Not sure if it is relevant but the ns91 namespace prefix used in the query is not defined in the service. Not sure if this is an internal notation of the validator though.
![grafik](https://github.com/opengeospatial/ets-wfs20/assets/34163838/7e2d8a6e-10cf-4d28-bad2-051592f2f1f0)

**Comment by dstenger** [comment]
Thank you for reporting.
We recognized problems with the XLink schema and are already working on it.
The issue reported here is most likely related to that.

**Comment by dstenger** [comment]
I just re-tested your service with https://cite.ogc.org/teamengine/ and the _get Features By Type_ test is successful.
We did not change anything on the Production environment. So, I assume that the problem was related to the remote XLink schema.
Can you please check if your problem is solved?

**Comment by JohannaOtt** [comment]
@dstenger I can confirm that the error messages are not occurring any longer when testing the WFS in the production instance.
