### ISSUE TITLE
WFS validation failling with Spatial filter errors

### ISSUE THREAD

**Issue by JohannaOtt** [opengeospatial/ets-wfs20#274]
**Describe the bug**
When testing [this WFS](https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wfs?ACCEPTVERSIONS=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) in the beta instance using version 1.41 of the WFS 2.0 validator, it fails several Spatial filter tests. From the error message, it is not clear what the issue is.

**To Reproduce**
1. Validate the WFS provided in the description with the WFS 2.0 test in version 1.41
2. Check the error messages in the Spatial filter section.

**Expected behavior**
Either there is an error in the test suite and the WFS should pass or the error messages should deliver a clear feedback on what the issue is.

**Screenshots**
![335996262-09a74055-b892-4863-94bb-94c8fc763237](https://github.com/opengeospatial/ets-wfs20/assets/34163838/404479a4-dd3f-401b-9bf6-6dea0224bddb)

**Additional context**
This issue is a follow up issue of https://github.com/opengeospatial/ets-wfs20/issues/247

**Comment by dstenger** [comment]
Thank you for reporting. I can reproduce the problem.
We will do further investigation.

**Comment by bpross-52n** [comment]
The features of the failing test do not have a geometry (feature type SpeciesDistributionDataset). For the failing tests, a test envelope is created out of the sampled feature data. However, as other feature types have data, this should be skipped rather than failed. We will create a fix for this and also enhance the error message.

**Comment by JohannaOtt** [comment]
@bpross-52n That is great news, thank you!
