### ISSUE TITLE
Add tests for spatial joins

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/ets-wfs20#28]
The relevant conformance class is **Spatial joins**: "The server shall implement join predicates using spatial operators." See A.1.12.

All tests are skipped if the service constraint `ImplementsSpatialJoins` is "FALSE" in the capabilities document.

**Comment by dstenger** [comment]
We have tested the current status of the Spatial Joins CC ETS. This are our results.

Method #findGeometryPropertiesToJoin [1] finds all geometry properties which can be used to execute a Spatial Join.
Why are the considered geometry data types limited to "AbstractSurfaceType", "AbstractCurveType" and "PointType"? For example, a feature type with geometry data type "GeometryPropertyType" is skipped.
If this limitation is necessary, it should be included in the documentation or test description.

In addition, the proceeding of "AbstractCurveType" and "PointType" is still missing.

 [1] org.opengis.cite.iso19142.joins.SpatialJoinTests#findGeometryPropertiesToJoin

**Comment by danieluct** [comment]
The current spatial join implementation imposes several requirements not mentioned in the standard (e.g.: there must be two distinct geometries in the feature types server by the WFS, neither of whom can be defined as `gml:AbstractGeometryType`, and, except in the case both of these are `AbstractCurveType,` one of them must be `AbstractSurfaceType`). Test should be skipped in case none of this requirements are fulfilled by the services.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

A test is implemented in the [SpatialJoinTests](https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java) class.

**Comment by dstenger** [comment]
@keshav-nangare Can you please check if A.1.12 of http://docs.opengeospatial.org/is/09-025r2/09-025r2.html is fully implemented?

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

I checked the above-referred document and it refers to the [OGC 09-026r2](https://docs.opengeospatial.org/is/09-026r2/09-026r2.html) document. Please find below screenshot from the referred document:

![image](https://user-images.githubusercontent.com/14732650/110759966-36138c00-8274-11eb-80a3-7846b7efbf33.png)

The A.7 and A.8 requirements from the OGC 09-026r2 document are as below and implemented in the ETS (https://github.com/opengeospatial/ets-wfs20/issues/28#issuecomment-790497175).

![image](https://user-images.githubusercontent.com/14732650/110760326-9b677d00-8274-11eb-9f68-cdedc05d1247.png)

**Comment by ghobona** [comment]
@keshav-nangare please implement a solution similar to PR https://github.com/opengeospatial/ets-wfs20/pull/177.

That is, if a geometry type is not supported then throw a SkipException.

**Comment by dstenger** [comment]
Meeting 2021-04-12:
PR #177 already contains the solution.
