### ISSUE TITLE
Provide a WFS 2.0 test instance to support joins

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs20#31]
Spatial Joins - intersects (plan to have the test ready: 20160516-20160531)

**Comment by dstenger** [comment]
We recently finished implementing Spatial Joins with the Intersect operator. This feature will be provided on the demo environment [1] when the next release is created.

We will continue working on implementing further operators for Spatial Joins.

[1] http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&request=GetCapabilities

**Comment by lgoltz** [comment]
Implementation of Spatial Joins was finished. Service: http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&request=GetCapabilities
