### ISSUE TITLE
Test lockSomeFeatures sends invalid GetFeatureWithLock request

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#32]
The Test lockSomeFeatures sends a request with two Filter:
```
<wfs:GetFeatureWithLock xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" expiry="60" lockAction="SOME"
  resultType="results" service="WFS" startIndex="0" version="2.0.0">
  <wfs:Query xmlns:ns84="http://www.deegree.org/app" typeNames="ns84:gns_iceland">
    <Filter xmlns="http://www.opengis.net/fes/2.0">
      <ResourceId rid="gns_iceland_-2643274" />
    </Filter>
    <Filter xmlns="http://www.opengis.net/fes/2.0">
      <ResourceId rid="gns_iceland_-2643274" />
      <ResourceId rid="gns_iceland_-2647445" />
      <ResourceId rid="gns_iceland_-2649558" />
      <ResourceId rid="gns_iceland_-2647523" />
      <ResourceId rid="gns_iceland_-2642297" />
      <ResourceId rid="gns_iceland_-2641862" />
      <ResourceId rid="gns_iceland_-2651772" />
      <ResourceId rid="gns_iceland_-2651068" />
      <ResourceId rid="gns_iceland_-2649172" />
      <ResourceId rid="gns_iceland_-2654429" />
    </Filter>
  </wfs:Query>
</wfs:GetFeatureWithLock>
```

In org.opengis.cite.iso19142.locking.GetFeatureWithLockTests.lockSomeFeatures() first Q1 is requested by adding a Filter using org.opengis.cite.iso19142.util.WFSRequest.addResourceIdPredicate(), this is repeated in the second part of the test requesting Q2. 

org.opengis.cite.iso19142.util.WFSRequest.addResourceIdPredicate() does not check if a filter already exists but adds one at the end inside the Query-Element.  

Expected is that the Request contains only one Filter.

**Comment by rjmartell** [comment]
In the second request the filter from the previous request was not cleared. Fixed in 1.23.
