### ISSUE TITLE
Order of locking tests results in unexpected test results

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#33]
We are wondering if the execution oder of the locking tests has side effects on the test results. Here, an example assuming a WFS providing one FeatureType:

First, the test lockAllFeaturesByType is executed:
- Parameters: GET , {​http://www.deegree.org/app}gns_iceland
- Start time: 11:32:30
- End time: 11:32:34 

All features are locked until now for 5 Minutes (the default value for expiry; as it is not set in [1]).

Then the test lockSomeFeatures is executed:
- Start time: 11:33:13
- End time: 11:33:13 

Expected is a GetFeatureWithLock-Response with at least two features (in the second part of the test; checking Q2).

But the feature collection is empty cause of the previously executed lock. 
What do you think about this?

[1] https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/locking/LockFeatureTests.java

**Comment by rjmartell** [comment]
Perhaps it would be better if each test class released all locks in an @AfterClass: method. Then there should be no interactions.

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please browse the WFS 2.0 reference implementations and check if there is any service which is failing the locking tests?

**Comment by ghobona** [comment]
We were unable to reproduce the error because the servers are no longer available.
