### ISSUE TITLE
Test "update Simple Property Value" does not consider decimal data type (plus various others)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#34]
If the test "update Simple Property Value" tries to update a property with data type decimal, an empty value is inserted as the data type is not supported by the ETS.

The relevant method is #newPropertyValue in [1]. The data types string, datetime and double are considered but other data types are missing.

Example for generated request:
```
<wfs:Transaction xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:tns="http://www.deegree.org/app"
  service="WFS" version="2.0.0">
  <wfs:Update typeName="tns:ft">
    <wfs:Property>
      <wfs:ValueReference>tns:property[1]</wfs:ValueReference>
      <wfs:Value />
    </wfs:Property>
    <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
      <fes:ResourceId rid="ft_-6187774" />
    </fes:Filter>
  </wfs:Update>
</wfs:Transaction>
```

[1] https://github.com/opengeospatial/ets-wfs20/blob/b6aded3cfa402628a41ae33bf5d66d01ddcbf127/src/main/java/org/opengis/cite/iso19142/transaction/Update.java

**Comment by rjmartell** [comment]
Yes, more cases need to be added to to the `newPropertyValue` method.

**Comment by rjmartell** [comment]
Fixed xsd:dateTime. Added support for xsd:date, xsd:decimal, xsd;anyURI, xsd:boolean
