### ISSUE TITLE
Test beforePeriod fails sometimes

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#42]
The test beforePeriod in Temporal filter CC fails sometimes. 

The test was applied to [1] , feature Type _gns_iceland,_ property _modify_date_. The date property  contains data from _1994-01-14_ to _2015-07-22_. The request send by the ets-wfs20 is 

``` xml
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0"
  count="10" service="WFS" startIndex="0" version="2.0.0">
  <wfs:Query xmlns:ns60="http://www.deegree.org/app" typeNames="ns60:gns_iceland">
    <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
      <fes:Before>
        <fes:ValueReference xmlns:tns="http://www.deegree.org/app">tns:modify_date</fes:ValueReference>
      <gml:TimePeriod xmlns:gml="http://www.opengis.net/gml/3.2"
        frame="http://www.iso.org/iso/iso8601" gml:id="TP01">
        <gml:beginPosition>1994-01-14T09:59:59.999Z</gml:beginPosition>
        <gml:endPosition>1994-01-14T22:59:59.999Z</gml:endPosition>
     </gml:TimePeriod>
      </fes:Before>
    </fes:Filter>
  </wfs:Query>
</wfs:GetFeature>
```

The WFS responses with an empty FeatureCollection as expected. The test should skip the oldest date property to avoid test failures. The test afterPeriod may be checked, too.  

[1] http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&request=GetCapabilities

**Comment by rjmartell** [comment]
What's happening here is that the the temporal interval spanned by a feature type in the data sample is split into a number of subintervals (2 by default) of approximately the same length. The _last_ subinterval is then set as the literal operand in the **beforePeriod** test; the _first_ subinterval is set as the operand in the **afterPeriod** test.
