### ISSUE TITLE
ETS modifies data of tested server

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#45]
Currently, the ETS modifies data of the tested server via WFS-T interface.
The ETS should undo all changes as test suites should not actively manipulate IUTs.

For example, a self join request with the touches operator returns more tuples after the ETS was executed.

**Comment by rjmartell** [comment]
The intent is that all changes are undone when the test methods in a class are finished (`@AfterClass`). For example:

* InsertTests::removeNewFeatures
* DeleteTests::restoreDeletedFeatures
* ReplaceTests::restoreModifiedFeatures
* Update::restoreModifiedFeatures

Warnings should appear in the ETS log file if any of these cleanup methods do not succeed. Are there any log entries indicating this is happening?

**Comment by dstenger** [comment]
Low priority.
Can be reopened if priority increases.
