### ISSUE TITLE
Enable HTML Reports

### ISSUE THREAD

**Issue by vleidl** [opengeospatial/ets-wfs20#47]
Is there a way to enable HTML reports for a test run? All that seems to be generated at the moment is `testng-results.xml`. Looking at `TestNGController.java`, I can see the default listeners are disabled.

**Comment by rjmartell** [comment]
The TEAM Engine harness uses the built-in XML reporter with a custom configuration. In release 1.26 and later W3C EARL results are also produced. There are plans to generate an HTML5 representation from the EARL output.

**Comment by rjmartell** [comment]
When running the test suite in an IDE, it is possible to enable the default listeners in TestNGController. In the TestNGController(String) constructor, change the third argument to `true` when creating a  TestNGExecutor (highlighted below).

this.executor = new TestNGExecutor(tngSuite.toString(), resultsDir.getAbsolutePath(), **true**);

**Comment by vleidl** [comment]
Thanks. That's what I ended up doing. I was primarily wondering if there's a way to turn them on without changing the code, but I don't think that's the case.
