### ISSUE TITLE
Is test supportedStoredQueryLanguages required?

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#49]
Currently, the test supportedStoredQueryLanguages in "Manage Stored Query"-CC fails against service [1]. The service does not describe the parameter language of the operation CreateStoredQuery.

In the specification we do not find a hint why this is mandatory in the capabilities:

```
8.3.5.2 Parameter domains (p. 49)
Table 12 defines the parameter domains that may be defined in the capabilities document of a web feature
service.
```

```
Table 12 (p. 50):
CreateStoredQuery, language, anyURI

Shall include the value urn:ogc:def:queryLanguage:OGC-WFS::WFSQueryExpression. May also include other
values indicating other languages are supported. This International Standard does not assign any meaning to
or describe any additional values that might be listed.
```

```
14.2.2.5.3 Implementation language (p. 82):

The language attribute of the wfs:QueryExpressionText element shall be used to specify the implementation
language of a component query expression.

Servers that conform to this International Standard shall support the value "urn:ogc:def:queryLanguage:OGC-
WFS::WFSQueryExpression" indicating that the component query expression is specified using the wfs:Query
(see 7.9.2.2) or wfs:StoredQuery (see 7.9.3.2) elements.
```

[1] http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&request=GetCapabilities

**Comment by rjmartell** [comment]
I believe the phrase "may be defined in the capabilities document" applies to non-standard parameter values that are supported (if any). The description column in Table 12 for CreateStoredQuery (language)  states (emphasis added): 

> **Shall include** the value urn:ogc:def:queryLanguage:OGC-WFS::WFSQueryExpression. May also include other values...

**Comment by lgoltz** [comment]
We added the parameter to the CreateStoredQuery operation in the capabilities. But the test still fails cause of a failure in the xpath of the test. (see #56)   .
