### ISSUE TITLE
Test updatedVersionHasSupersededPredecessor (Feature versions) requires optional attribute

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#52]
Test updatedVersionHasSupersededPredecessor requires the optional attribute "previousRid".

The test checks whether the response contains the attribute "previousRid" after an update request has been executed.

In the WFS 2.0 specification "previousRid" is not mentioned.

The FE 2.0 specification states the following (7.11.2 Encoding, p. 31):
```
The previousRid attribute may be used, in implementations that support versioning, 
to report the previous identifier of a resource.
```
This confirms that "previousRid" is an optional attribute.

The test should not base on an optional functionality.

**Comment by rjmartell** [comment]
Hm, it seems that we may have a different understanding of what the optional attributes in fes:ResourceId imply,

We know that WFS2-A.1.14 refers to A.2.11 (Versioning), which in turn depends on FES2-A.11.
Also, WFS2-A.2.11.2 does not restrict the use of any of the "version navigation controls" specified in FES2 so full support is implied. 

Now consider FES2, Table 1: "Implements ResourceId operator with the parameters that allow versions of resources to be queried (version, startTime, endTime)." Furthermore, FES2-A.11 does not constrain the implementation of the fes:ResourceId version navigation capability, implying full support. 

Recall that a client uses the fes:ResourceId predicate in a request to filter the version chain. The optionality in the schema type definition affects how a _client_ constructs a valid predicate--it doesn't really say anything about server support. 

So it would appear to be "all or nothing" on the server-side, but I'll check with the WFS SWG to confirm.

**Comment by rjmartell** [comment]
Ah, there is a typo in the WFS 2.0.2 spec. In cl. 15.3.5 (UpdateResults element):

> shall include the rid attribute whose value is the feature identifier of the newly created version of the 
feature and the oldRid attribute whose value shall be the identifier of previous version. 

There is no "oldRid" attribute in fes:ResourceId; this should be "previousRid".

**Comment by lgoltz** [comment]
Agreed... One more typo in the specification.  We will document this  at https://portal.opengeospatial.org/wiki/Testbed12/TB12CMP
