### ISSUE TITLE
Test updateSupersededVersion (Feature versions) is not backed by specification

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#54]
Test updateSupersededVersion is not backed by WFS 2.0 specification.

This test updates a superseded feature and expects an exception in the response.
This behaviour is not defined in WFS 2.0 specification.
Thus, it should not be tested by the test suite.

For example, the deegree WFS 2.0 RI candidate currently ignores the passed version value if a superseded version is updated. Instead, the valid version of the feature is updated.

In addition, the second update request looks like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<wfs:Transaction xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" service="WFS" version="2.0.0">
   <wfs:Update xmlns:ns85="http://www.deegree.org/app" handle="Update" typeName="ns85:osm_administrative">
      <wfs:Property>
         <wfs:ValueReference>gml:name[1]</wfs:ValueReference>
         <wfs:Value>nBEpHtLVTo FoIrhiTEcf</wfs:Value>
      </wfs:Property>
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:ResourceId rid="osm_administrative_25_version3" />
      </fes:Filter>
   </wfs:Update>
   <wfs:Update xmlns:ns63="http://www.deegree.org/app" handle="Update" typeName="ns63:osm_administrative">
      <wfs:Property>
         <wfs:ValueReference>gml:name[1]</wfs:ValueReference>
         <wfs:Value>nBEpHtLVTo
                                 FoIrhiTEcf</wfs:Value>
      </wfs:Property>
      <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
         <fes:ResourceId rid="osm_administrative_25_version3" />
      </fes:Filter>
   </wfs:Update>
</wfs:Transaction>
```

This request is not correct and the update element should just be included once in the transaction.

**Comment by rjmartell** [comment]
The update action shouldn't be duplicated--I'll fix that.

Note this statement in FES2: 7.11.2:

> If an implementation that references this International Standard supports versioning, the rid shall be a system generated hash containing a logical resource identifier and a version number. The specific details of the hash are implementation dependant [_sic_] and shall be opaque to a client.

I'm not quite sure what to make of this. If the details are supposed to be "opaque" why bother saying anything at all about how a version identifier is generated?

**Comment by rjmartell** [comment]
While the WFS spec doesn't explicitly address this update scenario it is likely to be a fairly common situation when versioning is supported. Suppose a user (user1) is updating a feature instance that as far as it knows is valid. However, before user1 submits the update request another user has already updated the instance such that the id (version) specified by user1 has been superseded. What should happen? A CR to clarify this may be in order.

We know (FES2: 7.11.2) that "The rid attribute specifies the id of the resource that shall be selected by the predicate."  I have simply assumed that "branching" is not allowed and that versioning is strictly linear.

**Comment by cmheazel** [comment]
"I'm not quite sure what to make of this. If the details are supposed to be "opaque" why bother saying anything at all about how a version identifier is generated?"

The rid identifies a Feature instance so it has to be unique within the service (ideally it would be globally unique).  One way to create such an identifier is to hash together the "logical resource identifier" (the Feature ID) with the version number of that feature.  Personally I have a problem with this approach.  It assumes a linear progression of version numbers.  Yet it is also legal to use time-boxed versioning (start and end time).  With time-boxes we do not have a progression of version numbers.  What to do?  Our escape clause is that the rid is “opaque”.  If the rid is opaque, then it by definition cannot be tested.  If it cannot be tested then it is not a requirement. 

Also note that with time-box versioning there can be overlap between versions.  I would not assume that versioning is always linear.

**Comment by cmheazel** [comment]
"Suppose a user (user1) is updating a feature instance that as far as it knows is valid. However, before user1 submits the update request another user has already updated the instance such that the id (version) specified by user1 has been superseded. What should happen?"

Throw an exception or corrupted the database.  A user should not be able to update a feature without first locking it.  There may be databases which can maintain content consistency in the face of multiple updates, but they are the exception rather than the rule.  And if they can maintain content consistency, then they can maintain version consistency as well.

**Comment by cmheazel** [comment]
On the subject of branching ----
One goal of SOM is to support what-if analysis.  So if our feature model represents not only what is but also what could be, and there are multiple alternatives that could be, will versions ever branch?  I wouldn't preclude it.

**Comment by dstenger** [comment]
Thank you for your comments. I agree to your thoughts and the specification can be made more specific by incorporating your ideas.

Nevertheless, in our opinion the test updateSupersededVersion should be omitted as it is not clearly backed by the specification. Shouldn't the ETS be as close to the specification as possible?

Our current implementation does not lead to any inconsistencies in the database. So, we see no urgent need to adjust it.
Of course, your described approach (exception is thrown) may be more user-friendly and so the discussion about enhancing the specification regarding that behaviour should continue.

**Comment by rjmartell** [comment]
Sounds like a CR may be in order. I'll ask the WFS SWG chair for some preliminary guidance.

**Comment by ghobona** [comment]
Closing this issue because the test implements Clause 15.3.5 of [OGC 09-025r2](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#306).
