### ISSUE TITLE
Schematron validator fails for already passing tests on WFS 2.0

### ISSUE THREAD

**Issue by dineshahuja** [opengeospatial/ets-wfs20#58]
I tested the WFS 2.0 on our implementation on 12 Jan for WFS 2.0 Test suite version 1.21 and tests were passing. Now when the test suite has been updated to 1.26 then some of the tests are failing with following message
"org.opengis.cite.validation.SchematronValidator.validate(Ljavax/xml/transform/Source;)Ljavax/xml/transform/Result;"  No further details are being provided in the failure.

Server URL "http://182.71.43.203:8080/GetFeature.ashx?service=WFS&version=2.0.0&request=GetCapabilities"

Following tests are failing which were passing earlier
"Get Capabilities_missing Service Param"
"Get Full Capabilities"
"Unknown Stored Query"
"Describe Unknown Feature Type"
"Capabilities Doc Corresponds To Wfs Simple"

I downloaded the logs as well.
[log.txt](https://github.com/opengeospatial/ets-wfs20/files/741662/log.txt)
[report_logs.txt](https://github.com/opengeospatial/ets-wfs20/files/741663/report_logs.txt)
[session.txt](https://github.com/opengeospatial/ets-wfs20/files/741664/session.txt)
[testlist.txt](https://github.com/opengeospatial/ets-wfs20/files/741665/testlist.txt)
[testng-results.txt](https://github.com/opengeospatial/ets-wfs20/files/741666/testng-results.txt)

**Comment by du002cl** [comment]
I also seeing this same issue. The above Server URL no longer works but you can look at the testng-results.txt file to see the responses that the tests thing are invalid. They do not look invalid to me.

**Comment by dstenger** [comment]
This issue seems to be related to #59. Issue 59 is fixed. Can you please check again?

**Comment by du002cl** [comment]
Issue is resolved, Thank you.
