### ISSUE TITLE
wfs20-ets (version 1.26) on cite.opengeospatial.org/teamengine produces unexpected test failures (probably due to faulty installation)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#59]
Following service is used for testing: http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&request=GetCapabilities
A few month ago it passed all tests of the test suite.

Now, 83 tests fail. The reasons are:
```
org.opengis.cite.validation.SchematronValidator.validate(Ljavax/xml/transform/Source;Z)Ljavax/xml/transform/Result; 
```
```
org.opengis.cite.geomatics.gml.GmlUtils.gmlToTemporalGeometricPrimitive(Lorg/w3c/dom/Element;)Lorg/opengis/temporal/TemporalGeometricPrimitive; 
```
```
org.opengis.cite.geomatics.TopologicalRelationships.isSpatiallyRelated(Lorg/opengis/cite/geomatics/SpatialOperator;Lorg/w3c/dom/Node;Lorg/w3c/dom/Node;)Z 
```

In addition, the service was tested on a local installation of the ETS (also version 1.26) and no test failed.
--> This is an environment related issue.

So, there could be an faulty installation on cite.opengeospatial.org/teamengine or there is an infrastructure related error.

**Comment by bermud** [comment]
@rjmartell , please take a look at this issue.

**Comment by bermud** [comment]
This was related to repeated jars. These jars were removed: commons-io-2.2.jar ets-gml32-1.21.jar ets-wfs11-1.25.jar geomatics-geotk-1.9.jar geomatics-geotk-1.10.jar jena-iri-1.1.2.jar schema-utils-1.7.jar slf4j-api-1.7.6.jar

**Comment by dstenger** [comment]
The same issue is occurring again.

**Comment by bermud** [comment]
When STA 1.0 was installed it copied schema-utils-1.7.jar. There is an older version schema-utils-1.8.jar. I deleted the older jar.

**Comment by dstenger** [comment]
Issue is fixed. Reported errors do not occur any more.
