### ISSUE TITLE
Test intersects Polygon and embedded Features

### ISSUE THREAD

**Issue by jeanmichelfischer** [opengeospatial/ets-wfs20#60]
If a FeatureType contains embedded FeatureTypes which as well have a geometry, in some cases the Test "intersects Polygon" fails.

For example this request delivers some "Districts" with a geometry as well, but outside the intersection Polygon:

http://services.interactive-instruments.de/cite-xs-410/simpledemo/cgi-bin/cities-postgresql/wfs?service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0&typenames=ns66:City&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns66,http://www.interactive-instruments.de/namespaces/demo/cities/4.0/cities),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3Cfes%3AFilter%20xmlns%3Ans66%3D%22http%3A%2F%2Fwww.interactive-instruments.de%2Fnamespaces%2Fdemo%2Fcities%2F4.0%2Fcities%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3AIntersects%3E%3Cfes%3AValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Fwww.interactive-instruments.de%2Fnamespaces%2Fdemo%2Fcities%2F4.0%2Fcities%22%3Etns%3Alocation%3C%2Ffes%3AValueReference%3E%3Cgml%3APolygon%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20gml%3Aid%3D%22d1e1%22%20srsName%3D%22urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326%22%3E%3Cgml%3Aexterior%3E%3Cgml%3ALinearRing%3E%3Cgml%3AposList%3E48.13%206.77%2048.13%2013.58%2053.54%2013.58%2053.54%206.77%2048.13%206.77%3C%2Fgml%3AposList%3E%3C%2Fgml%3ALinearRing%3E%3C%2Fgml%3Aexterior%3E%3C%2Fgml%3APolygon%3E%3C%2Ffes%3AIntersects%3E%3C%2Ffes%3AFilter%3E

So the test fails:
Predicate Intersects not satisfied by arguments. <gml:Polygon xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="d1e1" srsName="urn:ogc:def:crs:EPSG::4326"> <gml:exterior> <gml:LinearRing> <gml:posList>48.13 6.77 48.13 13.58 53.54 13.58 53.54 6.77 48.13 6.77</gml:posList> </gml:LinearRing> </gml:exterior> </gml:Polygon> <gml:Point xmlns:gml="http://www.opengis.net/gml/3.2" xmlns="http://www.interactive-instruments.de/namespaces/demo/cities/4.0/cities" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" gml:id="district.id.10.location.Geom_0" srsDimension="2" srsName="urn:ogc:def:crs:EPSG::4326"> <gml:pos>52.539720000000 13.584280000000</gml:pos> </gml:Point>

but the Geometry tested is is not part of the FeatureType requested, but a part of an embedded FeatureType.

It might be better to test only the Geometry of the FeatureType which is requested and not the geometries of embedded Features.

**Comment by keshav-nangare** [comment]
@jeanmichelfischer 

Can you please provide the service to reproduce this issue?

**Comment by jeanmichelfischer** [comment]
@keshav-nangare 
The service from my first post is still up and running. Maybe it was not reachable all time?

**Comment by dstenger** [comment]
@jeanmichelfischer
I tried to open [1] with web browser but I am getting a `502 Proxy Error`. Can you please check this?

[1] http://services.interactive-instruments.de/cite-xs-410/simpledemo/cgi-bin/cities-postgresql/wfs?service=WFS&version=2.0.0&request=GetCapabilities

**Comment by jeanmichelfischer** [comment]
I checked and it should be reachable now.

**Comment by dstenger** [comment]
The pull request was merged.

However, I still get failures with reason `java.lang.AssertionError: Unexpected HTTP status code. expected <br>[200] but found <br>[400]` for several `intersects Polygon` tests.
If you still have any problems, please open a new issue.

Please note that this fix has not been released and installed on any environment, yet. So, you might use the master branch and install the test suite by yourself or you can wait for the release and installation on Beta environment.
