### ISSUE TITLE
Test assumes we have a PropertyName called "name"

### ISSUE THREAD

**Issue by du002cl** [opengeospatial/ets-wfs20#61]
This test:

> **Name**: gmlNameIsNull
> **Description**: See ISO 19143: 7.7.3.5
> **Signature**: gmlNameIsNull(org.opengis.cite.iso19142.ProtocolBinding, javax.xml.namespace.QName)[pri:0, instance:org.opengis.cite.iso19142.basic.filter.PropertyIsNullOperatorTests@18581c1d]
> **Parameters**: POST , {http://www.mapinfo.com/wfs}World

Is making the following request:
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS" startIndex="0" version="2.0.0">
	<wfs:Query xmlns:ns5="http://www.mapinfo.com/wfs" typeNames="ns5:World">
		<Filter xmlns="http://www.opengis.net/fes/2.0">
			<PropertyIsNull>
				<ValueReference xmlns:gml="http://www.opengis.net/gml/3.2">gml:name</ValueReference>
			</PropertyIsNull>
		</Filter>
	</wfs:Query>
</wfs:GetFeature>
```

2 Questions

1. Why is it using the gml namespace for the value reference? Shouldnt it be using the namespace of the PropertyName (http://www.mapinfo.com/wfs)?
2. Why is it using "name"? This FeatureType does not have that property name, nor is it reported in a DescribeFeatureType.

The above information also applies for the GET version of this test.
As far as I understand the test suite does not have any data requirements.

Here is the session: http://cite.opengeospatial.org/teamengine/reports/mideveloper/s0211/html/

**Comment by jmfischer** [comment]
For 2. Just a clue:
https://ibin.co/3Nbj0VbcD8v4.png

**Comment by lgoltz** [comment]
@jmfischer You are right. `gml:name` is one of the properties inherited by AbstractFeatureType. Therefor it should be requestable for each feature type. 

As far as I see this is not bug and the issue can be closed.

**Comment by jeanmichelfischer** [comment]
@lgoltz but gml:name is optional 0..many, so maybe nevertheless a bug?

**Comment by lgoltz** [comment]
The test is pretty lax. It is checked, that the response does not contain the requested property. Cause the request contains a filter PropertyIsNull filter this should be fulfilled even if the response is empty. The cardinality of the property is not important at this point.
