### ISSUE TITLE
Add conformance class configuration into the wfs20 test

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wfs20#64]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
Branch: https://github.com/lat-lon/ets-wfs20/tree/defineBasicConformanceClasses-64

Fixed with commit: https://github.com/lat-lon/ets-wfs20/commit/f4a79d2f4ba5d99309730c6d0c9496ca7118f154

**Comment by dstenger** [comment]
Pull request was created: #67

**Comment by dstenger** [comment]
WFS 2.0.2 specification, chapter 2 states following:

> Table 1 specifies the conformance classes defined by this International Standard and the tests specified in Annex A that shall be satisfied in order to comply with each class. The only mandatory class, that all implementation of this standard must provide is the “Simple WFS” class. All other classes are optional.

This means that "Basic WFS" conformance class has to be removed from test suite configuration option "BasicConformanceClasses".

@bermud Do you agree?

**Comment by dstenger** [comment]
Decision: Simple WFS is the minimum.

**Comment by dstenger** [comment]
Remove Basic WFS from BasicConformanceClasses configuration: https://github.com/lat-lon/ets-wfs20/commit/c9f7257a8be2b5b9a34af1c347eb7965f667cc5c
