### ISSUE TITLE
Probably unsupported CRS EPSG:5514

### ISSUE THREAD

**Issue by MichalMed** [opengeospatial/ets-wfs20#66]
I was testing WFS service using INSPIRE validation service based on TeamEngine. http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID18b3511c-0afc-4bd2-a82b-7e58bb809e21.html

After some discussion about the topic (https://github.com/inspire-eu-validation/ets-repository/issues/93#issuecomment-328466806) I have found out, that in TeamEngine test is aborted with exception  "Default CRS not recognized. No transform for classification ?Krovak (North Orientated)?" Default CRS for the service is urn:ogc:def:crs:EPSG::5514. Is there any problem with this specific CRS?

**Comment by MichalMed** [comment]
According to https://github.com/opengeospatial/teamengine/issues/236 it looks like the issue is in the ETF webapp? CRS not supported. Am I right?

**Comment by lgoltz** [comment]
Yes, it is a bug in the ETS WFS 2.0.

**Comment by lgoltz** [comment]
Can be reproduced with http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=wfs&VERSION=2.0.0

**Comment by lgoltz** [comment]
Geotoolkit 3.21 is used:
```
[INFO] org.opengis.cite:ets-wfs20:jar:1.28-SNAPSHOT
[INFO] +- org.opengis.cite:ets-gml32:jar:1.25:compile
[INFO] |  +- com.sun.jersey:jersey-client:jar:1.19:compile
[INFO] |  |  \- com.sun.jersey:jersey-core:jar:1.19:compile
[INFO] |  |     \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  \- org.opengis.cite:geomatics-geotk:jar:1.14:compile
[INFO] |     +- org.geotoolkit.pending:geotk-xml-gml:jar:3.21:compile
[INFO] |     |  +- org.geotoolkit:geotk-metadata-sql:jar:3.21:compile
[INFO] |     |  +- org.geotoolkit.pending:geotk-temporal:jar:3.21:compile
[INFO] |     |  |  \- org.geotoolkit.pending:geotk-utility-pending:jar:3.21:compile
[INFO] |     |  +- org.geotoolkit.pending:geotk-geometry:jar:3.21:compile
[INFO] |     |  +- org.opengis:geoapi-pending:jar:3.1-M04:compile
[INFO] |     |  +- org.geotoolkit:geotk-xml-base:jar:3.21:compile
[INFO] |     |  \- javax.measure:jsr-275:jar:0.9.3:compile
[INFO] |     +- org.geotoolkit.pending:geotk-jtswrapper:jar:3.21:compile
[INFO] |     |  \- org.geotoolkit:geotk-utility:jar:3.21:compile
[INFO] |     +- com.vividsolutions:jts:jar:1.13:compile
[INFO] |     +- org.geotoolkit:geotk-epsg:jar:3.21:runtime
[INFO] |     |  +- org.geotoolkit:geotk-referencing:jar:3.21:compile
[INFO] |     |  +- java3d:vecmath:jar:1.5.2:compile
[INFO] |     |  +- org.geotoolkit:geotk-metadata:jar:3.21:compile
[INFO] |     |  \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |     \- org.apache.derby:derby:jar:10.10.2.0:runtime
```

**Comment by dstenger** [comment]
We should check whether this CRS is supported in newer versions of Geotoolkit and update the dependency then.

**Comment by keshav-nangare** [comment]
This issue is related to wfs20 test (not in teamengine) so below is code snippet which is not able to recognize the requested CRS.

https://github.com/opengeospatial/ets-wfs20/blob/9151fcc1cbe2c50089707c7de6414af31708dcc3/src/main/java/org/opengis/cite/iso19142/FeatureTypeInfo.java#L141

I have updated the version of the Geotoolkit but still getting the same error.

**Comment by dstenger** [comment]
As a third party library does not support this CRS, a fix will be quite complex.

Is it a problem for you to change the default CRS. Also, you can always refer to this bug in the test suite to emphasize that this failure is not correct.

**Comment by dstenger** [comment]
# Functional test

* Start Docker Container via `mvn clean install docker:run -Pdocker`.
* Execute tests with http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=wfs&VERSION=2.0.0.
* No test failures related to EPSG code.
