### ISSUE TITLE
Dataset linkage in metadata

### ISSUE THREAD

**Issue by MichalMed** [opengeospatial/ets-wfs20#68]
http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDe53bacc7-6a12-4e80-aec1-c7d2ca38db8d.html

I've got following error:

> XML document 'metadata_CP_opraveny.xml', record 'CZ-00025712-CUZK_SERIES-MD_CP': The metadata record has a linkage property, which references a resource at 'http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?' that is not one of the recognised network services, i.e. not a wfs:WFS_Capabilities (WFS 2.0), wms:WMS_Capabilities (WMS 1.3.0), wcs:Capabilities (WCS 2.0), sos:Capabilities (SOS 2.0) or atom:feed (ATOM feed). The name of the root element is 'ExceptionReport' in namespace 'http://www.opengis.net/ows/1.1'. Please review the resource to check that it meets the linkage requirements.

In the metadata, sources are really as listed, but the exception given is just the requirement for parameters. The link refers to end-point of the service, its type is properly described by protocol http://services.cuzk.cz/registry/codelist/OnlineResourceProtocolValue/OGC:WFS-2.0.0.

I suppose its right, but better ask.

**Comment by jonherrmann** [comment]
@MichalMed 

The ETF validator uses different test engines (like the OGC TEAM engine) to test INSPIRE datasets, metadata and services. The only case where the OGC TEAM engine is used, is when you run the test suite "WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite" against your (INSPIRE) service. This is also reflected in the Test Suites "Author" and the "Reference" property that fade in when you switch the "Level of Detail" to "All details".

As you can see in your report, the OGC TEAM engine is not used and your report will cause confusion here. Please close this issue. If you are not sure where to post issues then please create them in the INSPIRE ETS repository.

**Comment by MichalMed** [comment]
I'm really sorry, I accidently opened it here instead of INSPIRE ETS. Closing and aplogizing.
