### ISSUE TITLE
Data availability tests has opaque failures

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#69]
The data availability precondition is opaque in that it might fails for a host of other reasons, without reporting what the actual problem is. Examples found debugging GeoServer:

- The constraints reporting SOAP, XML and KVP binding support reported "true" instead of "TRUE" as the value. The internal checks found no bindings and merrily reported "no data", without any explanation. This test should be configured on its own
- If the first binding tried fails the rest is skipped because an exception is thrown, see here:
  https://github.com/opengeospatial/ets-wfs20/blob/e4d7d143398400c0b0642c4213d0916ab674374e/src/main/java/org/opengis/cite/iso19142/util/DataSampler.java#L258
  Again the tester is left with a criptic error message and little clue as to what might be going on (the notion that a failing binding disables everything else is not "obvious")

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by lgoltz** [comment]
As far as I understand I would propose to improve the precondition test SuitePreconditions.dataAreAvailable() as follows:

 * If a general problem occurs (e.g. no binding is available) the precondition fails with a detailed failure message 
 * If no data are available from any feature type  the precondition fails with a detailed failure message for each feature type
 * If at least one of the feature types provided by the service contains data the precondition does **not fail**. The tester is **not** informed about details why other feature types may not be used.

**Comment by aaime** [comment]
Looks good to me (but maybe log anyways somewhere why a certain feature type was discarded?)

**Comment by lgoltz** [comment]
> Looks good to me (but maybe log anyways somewhere why a certain feature type was discarded?)

This can be logged in the teamengine log file, of course. But I think there is no option to pass this information to the Web GUI (and REST) result.

**Comment by lgoltz** [comment]
Implementation of https://github.com/opengeospatial/ets-wfs20/issues/69#issuecomment-347473391 in PR #93.
