### ISSUE TITLE
SOAP tests use version 1.1, but WFS specification has been modified to require 1.2 instead

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#70]
See:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#412
and:
https://portal.opengeospatial.org/files/54916

**Comment by aaime** [comment]
It's a bit more confusing.. the specification reports a SOAP 1.1 syntax withing a SOAP 1.2 namespace:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#418

However a SOAP 1.2 fault has an entirely different structure:
https://www.w3.org/TR/soap12-part1/#soapfault

**Comment by aaime** [comment]
Also opened a ticket here: http://ogc.standardstracker.org/show_request.cgi?id=531

**Comment by aaime** [comment]
Yes, as far as I can tell the Fault section had only the namespace updated, but not the XML, which should look something like following (taken from the W3C spec):

````
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"
              xmlns:m="http://www.example.org/timeouts"
              xmlns:xml="http://www.w3.org/XML/1998/namespace">
 <env:Body>
  <env:Fault>
   <env:Code>
     <env:Value>env:Sender</env:Value>
     <env:Subcode>
      <env:Value>m:MessageTimeout</env:Value>
     </env:Subcode>
   </env:Code>
   <env:Reason>
     <env:Text xml:lang="en">Sender Timeout</env:Text>
   </env:Reason>
   <env:Detail>
     <m:MaxTime>P5M</m:MaxTime>
   </env:Detail>    
  </env:Fault>
 </env:Body>
</env:Envelope>
````

The thing is, the example in the spec would be important to figure out how to fill the above in the context of a OGC request.

**Comment by lgoltz** [comment]
As far as I see from a code analysis  the request are send in SOAP version 1.1 even though the service is WFS 2.0.2:
https://github.com/opengeospatial/ets-wfs20/blob/095d9e8f17311b7636e051241e4b0c99d99ce216/src/main/java/org/opengis/cite/iso19142/util/WFSClient.java#L409

This must be changed to request SOAP 1.2 if WFS is 2.0.2.
The SOAP request seems to be fine for both versions.

I assume that there could be failures to assert a SOAP 1.2 response in case of an exception.  But as mostly an exception is checked with an XPath like `//ows:Exception/@exceptionCode = 'InvalidParameterValue'`, this should be an individual case. 

This could be a valid example for a SOAP fault (if you agree you could add this as proposal to the issue in the OGC tracker):
```
<soap:Fault xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Code>
    <soap:Value>soap:Sender</soap:Value>
    <soap:Subcode>
      <soap:Value>InvalidParameterValue</soap:Value>
    </soap:Subcode>
  </soap:Code>
  <soap:Reason>
    <soap:Text xml:lang="en">A service exception was encountered.</soap:Text>
  </soap:Reason>
    <soap:Detail>
      <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows">
            …
      </ows:ExceptionReport>
   </soap:Detail>
</soap:Fault>
```

@aaime Can you already provide a public WFS 2.0.2 service supporting SOAP? Which problems do you see in the test suite?

**Comment by aaime** [comment]
@lgoltz the usual service I gave in the other tickets should eat both SOAP 1.1 and 1.2, but right now it follow spec and returns a schema invalid fault if you use SOAP 1.2.
I don't have a service declaring 2.0.2, rather avoid that as the spec changed in backwards incompatible ways and we try hard to avoid those changes (trying to avoid having ifs in the code to tell apart the two cases).

I've updated the OGC ticket with your suggestion

**Comment by aaime** [comment]
By the way, suite wise, I guess the problem might be that it should tell apart WFS 2.0 and 2.0.2 and use the right SOAP version accordingly.
