### ISSUE TITLE
tranverseResultsSetInBothDirections assumes the dataset has at least 4 features

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#71]
This is hard coded in the test. However picking the WFS 1.1 sample data and using it to run the tests (any legit dataset should do right?) makes this test fail because EntitéGénérique only has 3 features:
https://github.com/opengeospatial/ets-wfs20/blob/b816b104f9af2639edd98a8b0fb7807c10628ce3/src/main/java/org/opengis/cite/iso19142/paging/PagingTests.java#L100

Maybe the test should do a GetFeature without the count, see how many features are returned, and set a count based on that (and probably skip the test if the dataset is empty)

**Comment by lgoltz** [comment]
Thank you for reporting. I popose to change the test as follows:
1. Find a FeatureType with at least 2 features
   * skip the test if no FeatureType satisfies this requirement
1. Execute the test::
   * GetFeature request with `count=1`
     * Response must contain `@next`
   * Request with value of `@next`
     * Response must contain `@previous`
   * Request with value of `@previous`
     * Features must be the same as in first request

**Comment by aaime** [comment]
Sounds like a good plan!

**Comment by lgoltz** [comment]
Fixed with https://github.com/opengeospatial/ets-wfs20/pull/77/commits/b47a82dcfce8df6fb96211efb13500b5487c6106 and https://github.com/opengeospatial/ets-wfs20/pull/77/commits/733fee1f548728da82b965638cad4b55531a9f6d.

Not tested yet as no service supporting paging available.

**Comment by dstenger** [comment]
@aaime Can you provide a test service?

**Comment by aaime** [comment]
The usual one should do:
http://cloudsdi.geo-solutions.it/geoserver/sf/ows?service=wfs&request=GetCapabilities

**Comment by dstenger** [comment]
Service referenced in https://github.com/opengeospatial/ets-wfs20/issues/71#issuecomment-350702089 was used.

However, following error occurs:
```
java.lang.AssertionError: Node has unexpected <br><br>[local name] value. expected <br><br>[FeatureCollection] but found <br><br>[ExceptionReport] 
```

Request:
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="1" service="WFS" startIndex="0"
                version="2.0.0">
   <wfs:Query xmlns:ns75="http://cite.opengeospatial.org/gmlsf"
              typeNames="ns75:EntitéGénérique"/>
</wfs:GetFeature>
```

Response:
```
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1"
                     xmlns:xs="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     version="2.0.0"
                     xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://cloudsdi.geo-solutions.it:80/geoserver/schemas/ows/1.1.0/owsAll.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
      <ows:ExceptionText>Feature type sf:EntitÃ©GÃ©nÃ©rique unknown</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

**Comment by dstenger** [comment]
Looks like an encoding problem of TEAM Engine. If request is sent directly via HTTP client, a response with feature collection is returned.

@aaime Were you able to successfully execute the test on your environment?

**Comment by aaime** [comment]
I was, but used the TestNG runner, not the full TeamEngine web application. Also, I'm running on Linux, the default encoding is UTF-8 (in case the system just picks and uses the default platform encoding, changing platform would change the results).

**Comment by lgoltz** [comment]
Created new ticket for the problem reported in https://github.com/opengeospatial/ets-wfs20/issues/71#issuecomment-350733524: #86

**Comment by lgoltz** [comment]
@aaime As I'm not sure if you receive notifications from #86: Could you take a look at https://github.com/opengeospatial/ets-wfs20/issues/86#issuecomment-352992445
