### ISSUE TITLE
Complaince failed if there is no dataset supporting nillable properties

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#72]
The current propertyIsNil test fails if:

- There is no dataset with nillable properties
- There is a nillable property, but no actual null value in the dataset (all are populated with actual values)

See:
https://github.com/opengeospatial/ets-wfs20/blob/a565e6d9fb712ee8a3acc49d73040ef4ebcc2dd7/src/main/java/org/opengis/cite/iso19142/basic/filter/PropertyIsNilOperatorTests.java#L105

However, the ETS makes no such requirement, and a server could:

- Have a fixed custom data set that has no nillable properties
- Be reporting nillable properties as simply having minOccurs=0 and then omitting the element

In those cases the test should be skipped instead of failed (IMHO at least)

**Comment by lgoltz** [comment]
Thank you for reporting. 
As this test is part of the conformance class "Basic WFS" there is no requirement to pass the test for certifying (only the conformance class "Simple WFS" is required). 
So I agree with the proposal to skip the test in case there is no dataset with nillable properties. 

The second case (no actual null value) is more complicated as it is required to check when the test fails:
 * When a feature (with mandatory nillable property) does not contain the property?
 * When a feature (with mandatory nillable property) contains the property, but it is empty?

A solution could be to allow the tester to enter a FeatureType and property which satisfies the requirement of the test (property is nillable and contains nilled values).

**Comment by aaime** [comment]
The test code is already scanning the datasets to check ranges of time based values, so I guess the same could be done to figure out if a dataset contains nulls.

As for the tests, what I had in mind (and it might be wrong) is the following:

- From the DescribeFeatureType there is no nillable property -> skip the tests
- From the DescribeFeatureType there is a nillable property but there is no actual nil data (from the scan above) -> skip the test
- There is nillable and there is nil values -> run the filters and check the outputs

The "complicated" case is when a schema declares that the property can be both omitted and nillable, allowing GetFeature to both skip the element or preserve it while using "nil", something like:
<xsd:element maxOccurs="1" minOccurs="0" name="COUNTRY" nillable="true" type="xsd:string"/>

In this case again the data scan should verify which implementation choice was used by the server, and run the tests only if there are actual element with xs:nil

**Comment by dstenger** [comment]
Proposal: Scan results and just execute the test if there is at least one instance of nillable properties.

**Comment by lgoltz** [comment]
As proposed the test was improved to check if a feature type/property is nillable and contains nilled values. Furthermore the test is executed for each binding and feature type now.

PR: #89
