### ISSUE TITLE
Tests expecting OperationProcessingFailed along with a 400/403

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#73]
This test expects a return of OperationProcessingFailed with a 400 or 403 code:

https://github.com/opengeospatial/ets-wfs20/blob/d5b632ea04bd719e8e3a8917be0833e1b2ef00b2/src/main/java/org/opengis/cite/iso19142/basic/filter/ComparisonOperatorTests.java#L355

However, according to specification, OperationProcessingFailed must be paired with a 500:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#411

Given the input provided in the test is simply wrong, I'd go for InvalidParameterValue and 400, but it's just me (OperationProcessingFailed should be something unpredictable, and thus un-testable)

**Comment by mlaghi** [comment]
We have exactly the same behaviour as described by aaime, but we get it in another test: the org.opengis.cite.iso19142.simple.DescribeFeatureTypeTests.describeUnknownFeatureType
We return OperationProcessingFailed with error 500 where you seem to expect a 400 with "InvalidParameterValue"

**Comment by aaime** [comment]
I believe 400 with InvalidParameterValue is what the standard asks for in that case.
What I was describing is a situation where there is no consistency between the code (OperationProcessingFailed, in other terms, internal server error) and the expected HTTP status (400, or in other terms, user error)

**Comment by lgoltz** [comment]
In the footnote 400 and 403 are declared as deprecated:
```
2. The codes 400 & 403 may also be used but are deprecated.
```
The test should be enhanced to expect status code 500 as well as 400 and 403.

**Comment by lgoltz** [comment]
Fixed with https://github.com/opengeospatial/ets-wfs20/pull/76/commits/777971473833e27c1e4124d4ef196885c3f65740
