### ISSUE TITLE
PagingTests.getFeatureWithHitsOnly seems to demand an spec invalid behavior

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#78]
The test is the following:

https://github.com/opengeospatial/ets-wfs20/blob/b816b104f9af2639edd98a8b0fb7807c10628ce3/src/main/java/org/opengis/cite/iso19142/paging/PagingTests.java#L54

The comment at the top seems to be in line with the specification, numberReturned should be zero (hits is used to retrieve a number matched instead). However the implementation of the test tries to verify that numberReturned is 2 instead. From the spec:

> If the value of the resultType attribute is set to "hits" the server shall generate an empty response document containing no resource instances and the root element of the response container shall contain the count of the total number of resources that the operation found (see 7.7.4.2). The value for the number of resources presented in the response document (see 7.7.4.3) shall be set to zero."

Modifying it to test numberMatch=2 would also be in violation of the spec, because numberMatched according to spec represents the total number of features, not the count of the current page:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#74

**Comment by lgoltz** [comment]
The test follows the ATS from WFS 2.0, see http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#24 A.2.19.2.2.2 Paging response:

> Generate a feature collection response with a request having the resultType parameter set to "hits". Verify that the response is an empty feature collection with the numberMatched parameter containing a count of the number of features expected in the response. Verify that the next parameter is present in the response and its value is a URI that fetches the first set of results. 

The test verifies if numberReturned="2" is true for the result set retrieved with the request from the `@next` parameter. As far as I understand this is the expected behaviour described in the specification.

**Comment by aaime** [comment]
I believe the ATS is in contrast with what the spec says, see my links above

**Comment by lgoltz** [comment]
> I believe the ATS is in contrast with what the spec description says about the parameters and operations, see my links above. 

I think the question is how the URL in the `@next` attribute value is constructed in a GetFeature request with `resultType="hits"`. If it contains `resultType="results"` it is not in contrast with the spec, but follows the ATS.

**Comment by aaime** [comment]
You are obviously right, I did not notice that you were looking, and following, the "next" link (and the test fails on next existence check, because GeoServer does not generate said link).
I'm closing this report.
