### ISSUE TITLE
Test tries to create a stored query assuming inheritance support

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#79]
[CreateStoredQueryTests.testDuplicate](https://github.com/opengeospatial/ets-wfs20/blob/b816b104f9af2639edd98a8b0fb7807c10628ce3/src/main/java/org/opengis/cite/iso19142/querymgmt/CreateStoredQueryTests.java#L142) posts the following request for stored query creation:

https://github.com/opengeospatial/ets-wfs20/blob/c89fe8437af5698947a06772760d603285f9aef5/src/main/resources/org/opengis/cite/iso19142/querymgmt/CreateStoredQuery-GetFeatureByName.xml#L14

The query refers to "gml:AbstractFeature", which seems to make sense only if inheritance is supported (but there is no requirement to, and the capabilities document indicates it is not supported indeed).
I'd suggest to post a different query that does not make said assumption.

**Comment by aaime** [comment]
This other test also uses the same XML to first create and then try to drop a query:
https://github.com/opengeospatial/ets-wfs20/blob/773f7543b5870060d49acf4ac40111f6431be759/src/main/java/org/opengis/cite/iso19142/querymgmt/DropStoredQueryTests.java#L39

**Comment by lgoltz** [comment]
I think a feature type supported  by the sut should be used in the query instead of gml:AbstractFeature.

**Comment by aaime** [comment]
Makes sense.

**Comment by aaime** [comment]
Agreed
