### ISSUE TITLE
LockFeatureTest.resetNonExistentLock expects 403 but the specs demands 400

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#82]
Code here:

https://github.com/opengeospatial/ets-wfs20/blob/b816b104f9af2639edd98a8b0fb7807c10628ce3/src/main/java/org/opengis/cite/iso19142/locking/LockFeatureTests.java#L95

Reference table mapping ogc exception codes to HTTP status:
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#411

**Comment by lgoltz** [comment]
@aaime Why do you think that 400 is expected?

**Comment by aaime** [comment]
Because the specification in section 12.3.2 (part of LockFeature description) states:

> After the request is completed, the lockId shall be immediately released since no resources were locked. If that same lockId is used in a subsequent transaction an InvalidLockId exception shall be raised, as described in 7.5, since that lockId value no longer exists.

So, I cannot find where this statement in the comment comes from: "The WFS2 specification makes no distinction  between a non-existent and an expired lock in this context"
The quote above from the spec seems to suggest otherwise?

LockHasExpired is described as "The specified lock identifier on a Transaction or LockFeature operation has expired and is no longer valid." This one is explicit, talks about a lock that used to exist.

That said, implementation wise I also had a difficulty in telling apart expired locks from non existing ones, one might check the syntax of the lock to see if it has had a chance to exist before, and maybe one has a short lived list of expired locks, but in general, it's indeed problematic to tell apart a lockId that is expired from one that has never been valid.

Personally I would recommend to allow both responses (invalid or expired) in the test. Logically speaking, an implementation imho should return invalid unless it has proof that the lockId was once indeed valid. But that's just me :-)

**Comment by dstenger** [comment]
Propopsal: Both error codes are supported.
Before that, specification should be rechecked carefully.

**Comment by dstenger** [comment]
## Recheck of specification

Actually, the lines you are referencing refer to the special case of the lockId of a LockFeatureResponse which does not contain any features.
See sentences before your quote:
```
If the
lock request results in no features being locked, then a WFS shall respond with <wfs:LockFeatureResponse>
document that contains a value for the lockId attribute but that contains neither a wfs:FeaturesLocked element
nor a wfs:FeatureNotLocked element. In other words, an empty response. After the request is completed, the
lockId shall be immediately released since no resources were locked. If that same lockId is used in a
subsequent transaction an InvalidLockId exception shall be raised, as described in 7.5, since that lockId value
no longer exists.
```
Thus, for me it is no reason that InvalidLockId can always be used as a special use case is referred.

Meaning of both codes as described in table 3:
* InvalidLockId
```
The value of the lockId parameter on
a Transaction operation is invalid
because it was not generated by the
server.
```
* LockHasExpired
```
The specified lock identifier on a
Transaction or LockFeature
operation has expired and is no
longer valid.
```

These descriptions on combination with chapter ```12.2.4.2``` state (implicitly) that ```LockHasExpired``` must be expected by the test.

I agree that this is difficult on the side of implementation as all used lockId have to be saved (How long? Do they expire?).

**Comment by aaime** [comment]
If both codes are accepted by the test the issue will be solved, from my point of view (the issue being that the test currently only accepts as valid a "LockHasExpired"/403 combination).

**Comment by dstenger** [comment]
However, if we interpret the specification like that, the LockHasExpired exception will never occur/ must never be implemented as "InvalidLockId" will always be OK.
Of course, it can be argued that the specification is very vague and thus both exceptions should be accepted.

@lgoltz and @bermud What are your thoughts about this?

**Comment by lgoltz** [comment]
From my point of view the specification is very clear on the operation the exception should occur:
 * InvalidLockId: Transaction
 * LockHasExpired: Transaction or LockFeature

Furthermore the test resetNonexistentLock() tries to force the LockHasExpired exception. Maybe we should think about the way to achieve this. I propose the following scenario:

1. LockFeature request, locking features for 5 seconds
`<wfs:LockFeature ... expiry="15"/>`
1. Wait until lock is expired (10 seconds)
1. LockFeature request, resets the lock expiry (it is assumed that the lockId returned in step 1. is 1)
`<wfs:LockFeature ... lockId="1" expiry="15"/>`

The existing test could be changed by this test steps. It is not required to test for an invalid lock id, as this is not specified.

**Comment by aaime** [comment]
That would work and would make sense. 

If the specification actually asks for LockHasExpired result from a lock that never existed, then I would suggest to open a bug report against the spec itself, as the message is confusing at best for the user/software receiving it (especially given a InvalidLockId response also exists).

**Comment by lgoltz** [comment]
The test scenario proposed in https://github.com/opengeospatial/ets-wfs20/issues/82#issuecomment-351030203 is already implemented:
https://github.com/opengeospatial/ets-wfs20/blob/034f87bafde5dbbd2cc2913d8b2af3b018651db3/src/main/java/org/opengis/cite/iso19142/locking/GetFeatureWithLockTests.java#L126-L137

**Comment by lgoltz** [comment]
> If the specification actually asks for LockHasExpired result from a lock that never existed, ...

I didn't find anything like this.

As the test mentioned in https://github.com/opengeospatial/ets-wfs20/issues/82#issuecomment-351288375 already implements the test scenario described in https://github.com/opengeospatial/ets-wfs20/issues/82#issuecomment-351030203 I would suggest to remove the test completely.

**Comment by aaime** [comment]
Works for me :-)

**Comment by dstenger** [comment]
I agree. ```LockHasExpired``` exception is already tested in test ```lockAllQueryResults_20Seconds```. Thus, ```resetNonExistentLock``` becomes obsolete.
This also removes the unclear requirement from test suite if ```LockHasExpired``` exception must be thrown if lock has never existed.

**Comment by lgoltz** [comment]
Test removed: #94
