### ISSUE TITLE
GetFeatureWithLock.lockAllQueryResults_20Seconds issues an invalid LockFeature request

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs20#83]
According to the WFS 2.0.2 specification:

"If both a lockId parameter and one or more fes:AbstractQueryExpression elements are included in a LockFeature request then the server shall raise an OperationParsingFailed exception (see 7.5)"

However this test issues a request that has both:

https://github.com/opengeospatial/ets-wfs20/blob/034f87bafde5dbbd2cc2913d8b2af3b018651db3/src/main/java/org/opengis/cite/iso19142/locking/GetFeatureWithLockTests.java#L127

For the moment I've made GeoServer tolerant to that, the specification statement above seems to have been added in the corrigendum. Still, it might be good to fix the test so that it issues a valid request.

**Comment by lgoltz** [comment]
As this is new in WFS 2.0.2 I would propose the following changes;
* Remove  fes:AbstractQueryExpression from LockFeature operation in existing tests.
* Add new test with fes:AbstractQueryExpression **and** lockId if service is `WFS 2.0.2` and assert hat the the server raise an OperationParsingFailed exception.

**Comment by aaime** [comment]
Agreed, sounds like a good plan :)

**Comment by lgoltz** [comment]
@aaime Can you provide a service for testing?

**Comment by lgoltz** [comment]
>    Remove fes:AbstractQueryExpression from LockFeature operation in existing tests.

Implemented with https://github.com/opengeospatial/ets-wfs20/commit/47337fbac11e473b0299a23f8d9315982bde171b

 >  Add new test with fes:AbstractQueryExpression and lockId if service is WFS 2.0.2 and assert hat the the server raise an OperationParsingFailed exception.

Implemented with https://github.com/opengeospatial/ets-wfs20/commit/94fe4520f9f261f53acd6dd7efe158a1d682bfb2

PR: #91
