### ISSUE TITLE
tranverseResultsSetInBothDirections fails if feature type name contains special characters 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#86]
SUT: http://cloudsdi.geo-solutions.it/geoserver/sf/ows?service=wfs&request=GetCapabilities

Failure described in tranverseResultsSetInBothDirections

For details please see https://github.com/opengeospatial/ets-wfs20/issues/71#issuecomment-350733524.

**Comment by keshav-nangare** [comment]
@dstenger 

I have investigated this issue but its not related to teamengine. The wfs has the class to invoke all the 
 request.

I have added the charset=utf-8 in accept header but still its not working. If we observe the other request they containing with special characters are not failing.

e.g. http://cloudsdi.geo-solutions.it/geoserver/sf/ows?service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0&typenames=ns97:AggregateGeoFeature&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns97,http://cite.opengeospatial.org/gmlsf),xmlns(wfs,http://www.opengis.net/wfs/2.0)&resourceid=EntitéGénérique.f004

This issue is occurred only when the special characters are present in the parameter **`typenames`**.  Maybe the issue is with the test server(Not sure) need to check.

**Comment by lgoltz** [comment]
Here the request/response  send by the ETS (with ngrep):

```
GET /geoserver/sf/ows?service=WFS&version=2.0.0&request=GetFeature&count=1&startindex=0&typenames=ns67:Entit%C3%A9G%C3%A9n%C3%A9rique&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns67,http://cite.opengeospatial.org/gmlsf),xmlns(wfs,http://www.opengis.net/wfs/2.0) HTTP/1.1.
Cache-Control: no-cache.
Pragma: no-cache.
User-Agent: Java/1.8.0_121.
Host: cloudsdi.geo-solutions.it.
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2.
Connection: keep-alive.
.

##
HTTP/1.1 400 Bad Request.
Date: Tue, 19 Dec 2017 17:08:43 GMT.
Access-Control-Allow-Origin: *.
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Host.
X-Frame-Options: SAMEORIGIN.
Content-Type: application/xml.
Connection: close.
Transfer-Encoding: chunked.
.
229.
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://cloudsdi.geo-solutions.it:80/geoserver/schemas/ows/1.1.0/owsAll.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
    <ows:ExceptionText>Feature type sf:Entit....G....n....rique unknown</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
The exception also occurs with a REST Client, sending this request [1]  (or [2] with the decoded feature type). 

@aaime Can you take a look at the server? I don't see that the request is invalid.

[1] http://cloudsdi.geo-solutions.it//geoserver/sf/ows?service=WFS&version=2.0.0&request=GetFeature&count=1&startindex=0&typenames=ns67:Entit%C3%A9G%C3%A9n%C3%A9rique&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns67,http://cite.opengeospatial.org/gmlsf),xmlns(wfs,http://www.opengis.net/wfs/2.0)
[2] http://cloudsdi.geo-solutions.it//geoserver/sf/ows?service=WFS&version=2.0.0&request=GetFeature&count=1&startindex=0&typenames=ns67:EntitéGénérique&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns67,http://cite.opengeospatial.org/gmlsf),xmlns(wfs,http://www.opengis.net/wfs/2.0)

**Comment by aaime** [comment]
@lgoltz I'll try to have a look. Just to be sure, is this blocking only a subset of the tickets, or it's being a problem for all of them?

**Comment by lgoltz** [comment]
@aaime Thanks! As far as I see only this one test (tranverseResultsSetInBothDirections) is concerned. But there may by others.  And of course only feature type names with special characters are affected. It would be great if you could check if it the problem is located in the service. If not we have to take a closer look to the implementation of the ETS.

**Comment by aaime** [comment]
Looks like Apache ruins the requests while proxying them to Tomcat. We are looking into it (do you by any chance have suggestions about how to fix it?) but in the meantime we opened direct access on port 8080, so you can use this capabilities document for the time being:
http://cloudsdi.geo-solutions.it:8080/geoserver/sf/ows?service=WFS&version=2.0.0&request=GetCapabilities
E.g. this works:
http://cloudsdi.geo-solutions.it:8080/geoserver/sf/ows?service=WFS&version=2.0.0&request=GetFeature&count=1&startindex=0&typenames=ns67:Entit%C3%A9G%C3%A9n%C3%A9rique&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns67,http://cite.opengeospatial.org/gmlsf),xmlns(wfs,http://www.opengis.net/wfs/2.0)

**Comment by aaime** [comment]
In the meantime we also fixed Apache, so it works on port 80 now.
For internal rules we need to close the 8080 one, so can you go back to the original urls?

**Comment by lgoltz** [comment]
Great! I will test with the original url and close this issue if the problem is solved.

**Comment by lgoltz** [comment]
Works! Test was successful.
