### ISSUE TITLE
Additional KVP parameters are dropped

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-wfs20#98]
Additional KVP parameters seem to be dropped during the execution of the tests.

E.g. when submitting service http://services.kortforsyningen.dk/ps_inspire_gml321?REQUEST=GetCapabilities&SERVICE=WFS&ticket=nonExistingTicket , the test suite fails

![image](https://user-images.githubusercontent.com/11427611/36303612-96970e86-1304-11e8-81a8-d4336137a309.png)

So URL https://services.kortforsyningen.dk/ps_inspire_gml321?service=WFS&version=2.0.0&request=DescribeFeatureType was requested, and not https://services.kortforsyningen.dk/ps_inspire_gml321?service=WFS&version=2.0.0&request=DescribeFeatureType&ticket=nonExistingTicket When using a valid value for the ticket parameter, the service will reply with the GML application schema.

As far as I can see, the WFS standard actually allows for vendor-specific parameters to be supported. I am aware of the fact that it also says that

> A server shall produce valid results even if the VSPs are missing [...]

![image](https://user-images.githubusercontent.com/11427611/35619073-260611a0-067d-11e8-8ab1-692c88b097d9.png)

The concrete issue we have here, is that we support [user authentication through custom parameters](https://www.kortforsyningen.dk/content/login-on-the-danish-map-supplyen). So our services give an error when these parameters are missing (apart from the Capabilities, those anyone is allowed to see).

Is there any chance that the tests can be enhanced so that 

- user specified parameters are not dropped
- alternatively, one can configure whether or not to drop user specified parameters

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment]
Yes, you are right. Vendor specific parameters are currently dropped and there is no easy workaround.
We will do further research how to keep those parameters.

**Comment by dstenger** [comment]
This issue is similar to #108. Can you please test if pull request #117 solves your problem?

**Comment by heidivanparys** [comment]
@dstenger  Hi, I haven't got around yet to testing this again, but I just wanted to say that I haven't forgotten about this issue and I will test again after the summer holidays and get back to you.

**Comment by dstenger** [comment]
@heidivanparys 
#117 is already merged and installed on OGC Production and Beta environment.
Can you please confirm if this issue is solved, now?

**Comment by heidivanparys** [comment]
@dstenger I tested and this issue is solved!
